/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
* Definition file for class ClockAlarmListModel.
*
*/
// Created by TraceCompiler 2.2.4
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CLOCKALARMLISTMODELTRACES_H__
#define __CLOCKALARMLISTMODELTRACES_H__

#define KOstTraceComponentID 0x2002bce6

#define CLOCKALARMLISTMODEL_CLOCKALARMLISTMODEL_ENTRY 0x8a000a
#define CLOCKALARMLISTMODEL_CLOCKALARMLISTMODEL_EXIT 0x8a000b
#define DUP1_CLOCKALARMLISTMODEL_CLOCKALARMLISTMODEL_ENTRY 0x8a000c
#define DUP1_CLOCKALARMLISTMODEL_CLOCKALARMLISTMODEL_EXIT 0x8a000d
#define CLOCKALARMLISTMODEL_POPULATEMODEL_ENTRY 0x8a000e
#define CLOCKALARMLISTMODEL_POPULATEMODEL_EXIT 0x8a000f
#define CLOCKALARMLISTMODEL_SOURCEMODEL_ENTRY 0x8a0010
#define CLOCKALARMLISTMODEL_SOURCEMODEL_EXIT 0x8a0011
#define CLOCKALARMLISTMODEL_POPULATESOURCEMODEL_ENTRY 0x8a0012
#define CLOCKALARMLISTMODEL_POPULATESOURCEMODEL_EXIT 0x8a0013
#define CLOCKALARMLISTMODEL_CALCULATEREMAININGTIME_ENTRY 0x8a0014
#define CLOCKALARMLISTMODEL_CALCULATEREMAININGTIME_EXIT 0x8a0015
#define CLOCKALARMLISTMODEL_GETREMAININGSECONDS_ENTRY 0x8a0016
#define CLOCKALARMLISTMODEL_GETREMAININGSECONDS_EXIT 0x8a0017
#define CLOCKALARMLISTMODEL_UPDATESOURCEMODEL_ENTRY 0x8a0018
#define CLOCKALARMLISTMODEL_UPDATESOURCEMODEL_EXIT 0x8a0019
#define CLOCKALARMLISTMODEL_UPDATEREMAININGTIME_ENTRY 0x8a001a
#define CLOCKALARMLISTMODEL_UPDATEREMAININGTIME_EXIT 0x8a001b
#define CLOCKALARMLISTMODEL_GETDISPLAYSTRINGLISTFORALARMITEM_ENTRY 0x8a001c
#define CLOCKALARMLISTMODEL_GETDISPLAYSTRINGLISTFORALARMITEM_EXIT 0x8a001d
#define CLOCKALARMLISTMODEL_APPENDALARMTOMODEL_ENTRY 0x8a001e
#define CLOCKALARMLISTMODEL_APPENDALARMTOMODEL_EXIT 0x8a001f
#define CLOCKALARMLISTMODEL_UPDATEALARMDETAILS_ENTRY 0x8a0020
#define CLOCKALARMLISTMODEL_UPDATEALARMDETAILS_EXIT 0x8a0021
#define CLOCKALARMLISTMODEL_GETACTIVEALARMCOUNT_ENTRY 0x8a0022
#define CLOCKALARMLISTMODEL_GETACTIVEALARMCOUNT_EXIT 0x8a0023


#endif

// End of file

