/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
* Definition file for class ClockMainView.
*
*/
// Created by TraceCompiler 2.2.4
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CLOCKMAINVIEWTRACES_H__
#define __CLOCKMAINVIEWTRACES_H__

#define KOstTraceComponentID 0x2002bce6

#define CLOCKMAINVIEW_CLOCKMAINVIEW_ENTRY 0x8a002a
#define CLOCKMAINVIEW_CLOCKMAINVIEW_EXIT 0x8a002b
#define DUP1_CLOCKMAINVIEW_CLOCKMAINVIEW_ENTRY 0x8a002c
#define DUP1_CLOCKMAINVIEW_CLOCKMAINVIEW_EXIT 0x8a002d
#define CLOCKMAINVIEW_SETUPVIEW_ENTRY 0x8a002e
#define CLOCKMAINVIEW_SETUPVIEW_EXIT 0x8a002f
#define CLOCKMAINVIEW_SETUPAFTERVIEWREADY_ENTRY 0x8a0030
#define CLOCKMAINVIEW_SETUPAFTERVIEWREADY_EXIT 0x8a0031
#define CLOCKMAINVIEW_HANDLEALARMSTATUSCHANGED_ENTRY 0x8a0032
#define CLOCKMAINVIEW_HANDLEALARMSTATUSCHANGED_EXIT 0x8a0033
#define CLOCKMAINVIEW_REFRESHMAINVIEW_ENTRY 0x8a0034
#define CLOCKMAINVIEW_REFRESHMAINVIEW_EXIT 0x8a0035
#define CLOCKMAINVIEW_DISPLAYWORLDCLOCKVIEW_ENTRY 0x8a0036
#define CLOCKMAINVIEW_DISPLAYWORLDCLOCKVIEW_EXIT 0x8a0037
#define CLOCKMAINVIEW_ADDNEWALARM_ENTRY 0x8a0038
#define CLOCKMAINVIEW_ADDNEWALARM_EXIT 0x8a0039
#define CLOCKMAINVIEW_OPENSETTINGS_ENTRY 0x8a003a
#define CLOCKMAINVIEW_OPENSETTINGS_EXIT 0x8a003b
#define CLOCKMAINVIEW_HANDLEACTIVATED_ENTRY 0x8a003c
#define CLOCKMAINVIEW_HANDLEACTIVATED_EXIT 0x8a003d
#define CLOCKMAINVIEW_HANDLELONGPRESS_ENTRY 0x8a003e
#define CLOCKMAINVIEW_HANDLELONGPRESS_EXIT 0x8a003f
#define CLOCKMAINVIEW_DELETEALARM_ENTRY 0x8a0040
#define CLOCKMAINVIEW_DELETEALARM_EXIT 0x8a0041
#define CLOCKMAINVIEW_REMOVESNOOZEDALARM_ENTRY 0x8a0042
#define CLOCKMAINVIEW_REMOVESNOOZEDALARM_EXIT 0x8a0043
#define CLOCKMAINVIEW_UPDATEVIEW_ENTRY 0x8a0044
#define CLOCKMAINVIEW_UPDATEVIEW_EXIT 0x8a0045
#define CLOCKMAINVIEW_UPDATEPLACELABEL_ENTRY 0x8a0046
#define CLOCKMAINVIEW_UPDATEPLACELABEL_EXIT 0x8a0047
#define CLOCKMAINVIEW_HANDLEALARMLISTDISPLAY_ENTRY 0x8a0048
#define CLOCKMAINVIEW_HANDLEALARMLISTDISPLAY_EXIT 0x8a0049
#define CLOCKMAINVIEW_CHECKORIENTATIONANDLOADSECTION_ENTRY 0x8a004a
#define CLOCKMAINVIEW_CHECKORIENTATIONANDLOADSECTION_EXIT 0x8a004b
#define CLOCKMAINVIEW_SELECTEDMENUACTION_ENTRY 0x8a004c
#define CLOCKMAINVIEW_SELECTEDMENUACTION_EXIT 0x8a004d
#define CLOCKMAINVIEW_HANDLEMENUCLOSED_ENTRY 0x8a004e
#define CLOCKMAINVIEW_HANDLEMENUCLOSED_EXIT 0x8a004f
#define CLOCKMAINVIEW_SETMODEL_ENTRY 0x8a0050
#define CLOCKMAINVIEW_SETMODEL_EXIT 0x8a0051
#define CLOCKMAINVIEW_HIDEALARMLIST_ENTRY 0x8a0052
#define CLOCKMAINVIEW_HIDEALARMLIST_EXIT 0x8a0053
#define CLOCKMAINVIEW_UPDATEDATELABEL_ENTRY 0x8a0054
#define CLOCKMAINVIEW_UPDATEDATELABEL_EXIT 0x8a0055
#define CLOCKMAINVIEW_UPDATECLOCKWIDGET_ENTRY 0x8a0056
#define CLOCKMAINVIEW_UPDATECLOCKWIDGET_EXIT 0x8a0057
#define CLOCKMAINVIEW_CAPTURESCREENSHOT_ENTRY 0x8a0058
#define CLOCKMAINVIEW_CAPTURESCREENSHOT_EXIT 0x8a0059
#define CLOCKMAINVIEW_SAVEACTIVITY_ENTRY 0x8a005a
#define CLOCKMAINVIEW_SAVEACTIVITY_EXIT 0x8a005b
#define CLOCKMAINVIEW_EVENTMONITOR_ENTRY 0x8a0085
#define CLOCKMAINVIEW_EVENTMONITOR_EXIT 0x8a0086
#define CLOCKMAINVIEW_REMOVEACTIVITY_ENTRY 0x8a0087
#define CLOCKMAINVIEW_REMOVEACTIVITY_EXIT 0x8a0088


#endif

// End of file

