/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
* Definition file for class ClockWorldView.
*
*/
// Created by TraceCompiler 2.2.4
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CLOCKWORLDVIEWTRACES_H__
#define __CLOCKWORLDVIEWTRACES_H__

#define KOstTraceComponentID 0x2002bce6

#define CLOCKWORLDVIEW_CLOCKWORLDVIEW_ENTRY 0x8a005c
#define CLOCKWORLDVIEW_CLOCKWORLDVIEW_EXIT 0x8a005d
#define DUP1_CLOCKWORLDVIEW_CLOCKWORLDVIEW_ENTRY 0x8a005e
#define DUP1_CLOCKWORLDVIEW_CLOCKWORLDVIEW_EXIT 0x8a005f
#define CLOCKWORLDVIEW_SETUPVIEW_ENTRY 0x8a0060
#define CLOCKWORLDVIEW_SETUPVIEW_EXIT 0x8a0061
#define CLOCKWORLDVIEW_REFRESHCITYLIST_ENTRY 0x8a0062
#define CLOCKWORLDVIEW_REFRESHCITYLIST_EXIT 0x8a0063
#define CLOCKWORLDVIEW_UPDATECURRENTLOCATIONINFO_ENTRY 0x8a0064
#define CLOCKWORLDVIEW_UPDATECURRENTLOCATIONINFO_EXIT 0x8a0065
#define CLOCKWORLDVIEW_HANDLEITEMLONGPRESSED_ENTRY 0x8a0066
#define CLOCKWORLDVIEW_HANDLEITEMLONGPRESSED_EXIT 0x8a0067
#define CLOCKWORLDVIEW_HANDLEADDLOCATION_ENTRY 0x8a0068
#define CLOCKWORLDVIEW_HANDLEADDLOCATION_EXIT 0x8a0069
#define CLOCKWORLDVIEW_HANDLEDELETEACTION_ENTRY 0x8a006a
#define CLOCKWORLDVIEW_HANDLEDELETEACTION_EXIT 0x8a006b
#define CLOCKWORLDVIEW_HANDLESETASCURRENTLOCATIONACTION_ENTRY 0x8a006c
#define CLOCKWORLDVIEW_HANDLESETASCURRENTLOCATIONACTION_EXIT 0x8a006d
#define CLOCKWORLDVIEW_HANDLECITYSELECTED_ENTRY 0x8a006e
#define CLOCKWORLDVIEW_HANDLECITYSELECTED_EXIT 0x8a006f
#define CLOCKWORLDVIEW_SHOWALARMSVIEW_ENTRY 0x8a0070
#define CLOCKWORLDVIEW_SHOWALARMSVIEW_EXIT 0x8a0071
#define CLOCKWORLDVIEW_REFRESHWORLDVIEW_ENTRY 0x8a0072
#define CLOCKWORLDVIEW_REFRESHWORLDVIEW_EXIT 0x8a0073
#define CLOCKWORLDVIEW_LOADSECTION_ENTRY 0x8a0074
#define CLOCKWORLDVIEW_LOADSECTION_EXIT 0x8a0075
#define CLOCKWORLDVIEW_UPDATEALLLOCATIONINFO_ENTRY 0x8a0076
#define CLOCKWORLDVIEW_UPDATEALLLOCATIONINFO_EXIT 0x8a0077
#define CLOCKWORLDVIEW_SELECTEDMENUACTION_ENTRY 0x8a0078
#define CLOCKWORLDVIEW_SELECTEDMENUACTION_EXIT 0x8a0079
#define CLOCKWORLDVIEW_ADDCITYTOLIST_ENTRY 0x8a007a
#define CLOCKWORLDVIEW_ADDCITYTOLIST_EXIT 0x8a007b
#define CLOCKWORLDVIEW_ISDAY_ENTRY 0x8a007c
#define CLOCKWORLDVIEW_ISDAY_EXIT 0x8a007d
#define DUP1_CLOCKWORLDVIEW_ISDAY_EXIT 0x8a007e
#define CLOCKWORLDVIEW_GETCITYLISTDISPLAYSTRING_ENTRY 0x8a007f
#define CLOCKWORLDVIEW_GETCITYLISTDISPLAYSTRING_EXIT 0x8a0080
#define CLOCKWORLDVIEW_GETCITYLISTDECORATIONSTRING_ENTRY 0x8a0081
#define CLOCKWORLDVIEW_GETCITYLISTDECORATIONSTRING_EXIT 0x8a0082
#define CLOCKWORLDVIEW_UPDATECITYLIST_ENTRY 0x8a0083
#define CLOCKWORLDVIEW_UPDATECITYLIST_EXIT 0x8a0084


#endif

// End of file

