//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//


PRINT Run all t_unit_imapservermtm_server Tests 
LOAD_SUITE t_unit_imapservermtm_server
RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmConnect 			c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini
RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmConnectAndSync	c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini
RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmIsConnected		c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini
RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmCancelBackgSync	c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini
RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmBusy				c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini
RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmSelect			c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini
RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmSyncTree			c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini
RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmFullSync			c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini
RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmDisconnect		c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini

RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmFolderFullSync	c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini
RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmWaitForBackg		c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini
RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmRenameFolder		c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini
RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmUndeleteAll		c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini
RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmCancelOfflineOp	c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini

RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmUnsupportedCmds	c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini

RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmCopyToLocal		c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini
RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmCopyFromLocal		c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini
RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmCopyWithinService	c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini

RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmMoveToLocal		c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini
RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmMoveFromLocal		c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini
RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmMoveWithinService	c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini

RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmDeleteAll			c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini
RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmCreate			c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini
RUN_TEST_STEP	1000	t_unit_imapservermtm_server	TEFUnit.CTestImapServerMtmChange			c:\msgtest\Scripts\ImapUnit\t_unit_imapservermtm.ini

