// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __ANALOGCLOCKWIDGETTRACES_H__
#define __ANALOGCLOCKWIDGETTRACES_H__

#define KOstTraceComponentID 0x2002e715

#define ANALOGCLOCKWIDGET_ANALOGCLOCKWIDGET_ENTRY 0x8a0001
#define ANALOGCLOCKWIDGET_ANALOGCLOCKWIDGET_EXIT 0x8a0002
#define DUP1_ANALOGCLOCKWIDGET_ANALOGCLOCKWIDGET_ENTRY 0x8a0003
#define DUP1_ANALOGCLOCKWIDGET_ANALOGCLOCKWIDGET_EXIT 0x8a0004
#define ANALOGCLOCKWIDGET_CONSTRUCTPRIMITIVES_ENTRY 0x8a0005
#define ANALOGCLOCKWIDGET_CONSTRUCTPRIMITIVES_EXIT 0x8a0006
#define ANALOGCLOCKWIDGET_UPDATEPRIMITIVES_ENTRY 0x8a0007
#define ANALOGCLOCKWIDGET_UPDATEPRIMITIVES_EXIT 0x8a0008
#define ANALOGCLOCKWIDGET_TICK_ENTRY 0x8a0009
#define ANALOGCLOCKWIDGET_TICK_EXIT 0x8a000a
#define ANALOGCLOCKWIDGET_SETGEOMETRY_ENTRY 0x8a000b
#define ANALOGCLOCKWIDGET_SETGEOMETRY_EXIT 0x8a000c


#endif

// End of file

