// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __DIGITALCLOCKWIDGETTRACES_H__
#define __DIGITALCLOCKWIDGETTRACES_H__

#define KOstTraceComponentID 0x2002e715

#define DIGITALCLOCKWIDGET_DIGITALCLOCKWIDGET_ENTRY 0x8a001f
#define DIGITALCLOCKWIDGET_DIGITALCLOCKWIDGET_EXIT 0x8a0020
#define DUP1_DIGITALCLOCKWIDGET_DIGITALCLOCKWIDGET_ENTRY 0x8a0021
#define DUP1_DIGITALCLOCKWIDGET_DIGITALCLOCKWIDGET_EXIT 0x8a0022
#define DIGITALCLOCKWIDGET_TICK_ENTRY 0x8a0023
#define DIGITALCLOCKWIDGET_TICK_EXIT 0x8a0024
#define DIGITALCLOCKWIDGET_SETAMPM_ENTRY 0x8a0025
#define DIGITALCLOCKWIDGET_SETAMPM_EXIT 0x8a0026
#define DIGITALCLOCKWIDGET_RESIZEEVENT_ENTRY 0x8a0027
#define DIGITALCLOCKWIDGET_RESIZEEVENT_EXIT 0x8a0028
#define DIGITALCLOCKWIDGET_CREATEPRIMITIVES_ENTRY 0x8a0029
#define DIGITALCLOCKWIDGET_CREATEPRIMITIVES_EXIT 0x8a002a
#define DIGITALCLOCKWIDGET_UPDATEPRIMITIVES_ENTRY 0x8a002b
#define DIGITALCLOCKWIDGET_UPDATEPRIMITIVES_EXIT 0x8a002c


#endif

// End of file

