// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENSETTINGSVIEWTRACES_H__
#define __CALENSETTINGSVIEWTRACES_H__

#define KOstTraceComponentID 0x10282f26

#define CALENSETTINGSVIEW_CALENSETTINGSVIEW_ENTRY 0x8a0167
#define CALENSETTINGSVIEW_CALENSETTINGSVIEW_EXIT 0x8a0168
#define DUP1_CALENSETTINGSVIEW_CALENSETTINGSVIEW_ENTRY 0x8a0169
#define DUP1_CALENSETTINGSVIEW_CALENSETTINGSVIEW_EXIT 0x8a016a
#define CALENSETTINGSVIEW_LAUNCHPREVIOUSVIEW_ENTRY 0x8a016b
#define CALENSETTINGSVIEW_LAUNCHPREVIOUSVIEW_EXIT 0x8a016c
#define CALENSETTINGSVIEW_INITIALIZEFORM_ENTRY 0x8a016d
#define CALENSETTINGSVIEW_INITIALIZEFORM_EXIT 0x8a016e
#define CALENSETTINGSVIEW_REFRESHVIEW_ENTRY 0x8a016f
#define CALENSETTINGSVIEW_REFRESHVIEW_EXIT 0x8a0170


#endif

// End of file

