// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENEVENTLISTVIEWITEMTRACES_H__
#define __CALENEVENTLISTVIEWITEMTRACES_H__

#define KOstTraceComponentID 0x10282f26

#define CALENEVENTLISTVIEWITEM_CALENEVENTLISTVIEWITEM_ENTRY 0x8a0066
#define CALENEVENTLISTVIEWITEM_CALENEVENTLISTVIEWITEM_EXIT 0x8a0067
#define DUP1_CALENEVENTLISTVIEWITEM_CALENEVENTLISTVIEWITEM_ENTRY 0x8a0068
#define DUP1_CALENEVENTLISTVIEWITEM_CALENEVENTLISTVIEWITEM_EXIT 0x8a0069
#define CALENEVENTLISTVIEWITEM_CREATEITEM_ENTRY 0x8a006a
#define CALENEVENTLISTVIEWITEM_CREATEITEM_EXIT 0x8a006b
#define CALENEVENTLISTVIEWITEM_UPDATECHILDITEMS_ENTRY 0x8a006c
#define CALENEVENTLISTVIEWITEM_UPDATECHILDITEMS_EXIT 0x8a006d


#endif

// End of file

