// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENTHICKLINESDRAWERTRACES_H__
#define __CALENTHICKLINESDRAWERTRACES_H__

#define KOstTraceComponentID 0x10282f26

#define CALENTHICKLINESDRAWER_CALENTHICKLINESDRAWER_ENTRY 0x8a0171
#define CALENTHICKLINESDRAWER_CALENTHICKLINESDRAWER_EXIT 0x8a0172
#define DUP1_CALENTHICKLINESDRAWER_CALENTHICKLINESDRAWER_ENTRY 0x8a0173
#define DUP1_CALENTHICKLINESDRAWER_CALENTHICKLINESDRAWER_EXIT 0x8a0174
#define CALENTHICKLINESDRAWER_PAINT_ENTRY 0x8a0175
#define CALENTHICKLINESDRAWER_PAINT_EXIT 0x8a0176
#define CALENTHICKLINESDRAWER_HANDLETHEMECHANGE_ENTRY 0x8a018b
#define CALENTHICKLINESDRAWER_HANDLETHEMECHANGE_EXIT 0x8a018c


#endif

// End of file

