// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENPLUGINLABELTRACES_H__
#define __CALENPLUGINLABELTRACES_H__

#define KOstTraceComponentID 0x10282f26

#define CALENPLUGINLABEL_CALENPLUGINLABEL_ENTRY 0x8a0144
#define CALENPLUGINLABEL_CALENPLUGINLABEL_EXIT 0x8a0145
#define DUP1_CALENPLUGINLABEL_CALENPLUGINLABEL_ENTRY 0x8a0146
#define DUP1_CALENPLUGINLABEL_CALENPLUGINLABEL_EXIT 0x8a0147
#define CALENPLUGINLABEL_GESTUREEVENT_ENTRY 0x8a0148
#define CALENPLUGINLABEL_GESTUREEVENT_EXIT 0x8a0149


#endif

// End of file

