// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __NOTESDOCLOADERTRACES_H__
#define __NOTESDOCLOADERTRACES_H__

#define KOstTraceComponentID 0x20029f84

#define NOTESDOCLOADER_CREATEOBJECT_ENTRY 0x8a0001
#define NOTESDOCLOADER_CREATEOBJECT_EXIT 0x8a0002
#define DUP1_NOTESDOCLOADER_CREATEOBJECT_EXIT 0x8a0003
#define DUP2_NOTESDOCLOADER_CREATEOBJECT_EXIT 0x8a0004
#define DUP3_NOTESDOCLOADER_CREATEOBJECT_EXIT 0x8a0005
#define DUP4_NOTESDOCLOADER_CREATEOBJECT_EXIT 0x8a0006


#endif

// End of file

