/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
* Implementation file for class ClockSettingsView.
*
*/
// Created by TraceCompiler 2.2.4
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CLOCKSETTINGSVIEWTRACES_H__
#define __CLOCKSETTINGSVIEWTRACES_H__

#define KOstTraceComponentID 0x10005906

#define CLOCKSETTINGSVIEW_CLOCKSETTINGSVIEW_ENTRY 0x8a0022
#define CLOCKSETTINGSVIEW_CLOCKSETTINGSVIEW_EXIT 0x8a0023
#define DUP1_CLOCKSETTINGSVIEW_CLOCKSETTINGSVIEW_ENTRY 0x8a0024
#define DUP1_CLOCKSETTINGSVIEW_CLOCKSETTINGSVIEW_EXIT 0x8a0025
#define CLOCKSETTINGSVIEW_LOADSETTINGSVIEW_ENTRY 0x8a0026
#define CLOCKSETTINGSVIEW_LOADSETTINGSVIEW_EXIT 0x8a0027
#define CLOCKSETTINGSVIEW_HANDLEBACKACTION_ENTRY 0x8a0028
#define CLOCKSETTINGSVIEW_HANDLEBACKACTION_EXIT 0x8a0029
#define CLOCKSETTINGSVIEW_UPDATEPLACEITEM_ENTRY 0x8a002a
#define CLOCKSETTINGSVIEW_UPDATEPLACEITEM_EXIT 0x8a002b
#define CLOCKSETTINGSVIEW_UPDATEDATEITEM_ENTRY 0x8a002c
#define CLOCKSETTINGSVIEW_UPDATEDATEITEM_EXIT 0x8a002d
#define CLOCKSETTINGSVIEW_UPDATETIMEITEM_ENTRY 0x8a002e
#define CLOCKSETTINGSVIEW_UPDATETIMEITEM_EXIT 0x8a002f
#define CLOCKSETTINGSVIEW_HANDLEORIENTATIONCHANGED_ENTRY 0x8a0030
#define CLOCKSETTINGSVIEW_HANDLEORIENTATIONCHANGED_EXIT 0x8a0031
#define CLOCKSETTINGSVIEW_HANDLENETWORKTIMESTATECHANGE_ENTRY 0x8a0032
#define CLOCKSETTINGSVIEW_HANDLENETWORKTIMESTATECHANGE_EXIT 0x8a0033
#define CLOCKSETTINGSVIEW_SETUPVIEW_ENTRY 0x8a0034
#define CLOCKSETTINGSVIEW_SETUPVIEW_EXIT 0x8a0035
#define CLOCKSETTINGSVIEW_CREATEMODEL_ENTRY 0x8a0036
#define CLOCKSETTINGSVIEW_CREATEMODEL_EXIT 0x8a0037
#define CLOCKSETTINGSVIEW_POPULATEMODEL_ENTRY 0x8a0038
#define CLOCKSETTINGSVIEW_POPULATEMODEL_EXIT 0x8a0039
#define CLOCKSETTINGSVIEW_HANDLEAUTOTIMEUPDATECHANGE_ENTRY 0x8a003a
#define CLOCKSETTINGSVIEW_HANDLEAUTOTIMEUPDATECHANGE_EXIT 0x8a003b
#define CLOCKSETTINGSVIEW_HANDLEALARMSNOOZETIMECHANGED_ENTRY 0x8a003c
#define CLOCKSETTINGSVIEW_HANDLEALARMSNOOZETIMECHANGED_EXIT 0x8a003d
#define CLOCKSETTINGSVIEW_HANDLECLOCKTYPECHANGED_ENTRY 0x8a003e
#define CLOCKSETTINGSVIEW_HANDLECLOCKTYPECHANGED_EXIT 0x8a003f
#define CLOCKSETTINGSVIEW_EVENTMONITOR_ENTRY 0x8a0040
#define CLOCKSETTINGSVIEW_EVENTMONITOR_EXIT 0x8a0041
#define CLOCKSETTINGSVIEW_UPDATECLOCKTYPE_ENTRY 0x8a0070
#define CLOCKSETTINGSVIEW_UPDATECLOCKTYPE_EXIT 0x8a0071


#endif

// End of file

