/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
* Definition file for class ClockSettingsView.
*
*/
// Created by TraceCompiler 2.2.4
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __SETTINGSCUSTOMITEMTRACES_H__
#define __SETTINGSCUSTOMITEMTRACES_H__

#define KOstTraceComponentID 0x10005906

#define SETTINGSCUSTOMITEM_SETTINGSCUSTOMITEM_ENTRY 0x8a0042
#define SETTINGSCUSTOMITEM_SETTINGSCUSTOMITEM_EXIT 0x8a0043
#define DUP1_SETTINGSCUSTOMITEM_SETTINGSCUSTOMITEM_ENTRY 0x8a0044
#define DUP1_SETTINGSCUSTOMITEM_SETTINGSCUSTOMITEM_EXIT 0x8a0045
#define SETTINGSCUSTOMITEM_CREATEITEM_ENTRY 0x8a0046
#define SETTINGSCUSTOMITEM_CANSETMODELINDEX_ENTRY 0x8a0047
#define SETTINGSCUSTOMITEM_CANSETMODELINDEX_EXIT 0x8a0048
#define DUP1_SETTINGSCUSTOMITEM_CANSETMODELINDEX_EXIT 0x8a0049
#define SETTINGSCUSTOMITEM_RESTORE_ENTRY 0x8a004a
#define SETTINGSCUSTOMITEM_RESTORE_EXIT 0x8a004b
#define SETTINGSCUSTOMITEM_SETWEEKDAYSLIST_ENTRY 0x8a004c
#define SETTINGSCUSTOMITEM_SETWEEKDAYSLIST_EXIT 0x8a004d
#define SETTINGSCUSTOMITEM_CREATECUSTOMWIDGET_ENTRY 0x8a004e
#define SETTINGSCUSTOMITEM_CREATECUSTOMWIDGET_EXIT 0x8a004f
#define DUP1_SETTINGSCUSTOMITEM_CREATECUSTOMWIDGET_EXIT 0x8a0050
#define DUP2_SETTINGSCUSTOMITEM_CREATECUSTOMWIDGET_EXIT 0x8a0051
#define DUP3_SETTINGSCUSTOMITEM_CREATECUSTOMWIDGET_EXIT 0x8a0052
#define DUP4_SETTINGSCUSTOMITEM_CREATECUSTOMWIDGET_EXIT 0x8a0053
#define SETTINGSCUSTOMITEM_LAUNCHTIMEPICKER_ENTRY 0x8a0054
#define SETTINGSCUSTOMITEM_LAUNCHTIMEPICKER_EXIT 0x8a0055
#define SETTINGSCUSTOMITEM_HANDLEOKACTION_ENTRY 0x8a0056
#define SETTINGSCUSTOMITEM_HANDLEOKACTION_EXIT 0x8a0057
#define SETTINGSCUSTOMITEM_LAUNCHDATEPICKER_ENTRY 0x8a0058
#define SETTINGSCUSTOMITEM_LAUNCHDATEPICKER_EXIT 0x8a0059
#define SETTINGSCUSTOMITEM_LAUNCHCITYSELECTIONLIST_ENTRY 0x8a005a
#define SETTINGSCUSTOMITEM_LAUNCHCITYSELECTIONLIST_EXIT 0x8a005b
#define SETTINGSCUSTOMITEM_UPDATEPLACEITEM_ENTRY 0x8a005c
#define SETTINGSCUSTOMITEM_UPDATEPLACEITEM_EXIT 0x8a005d
#define SETTINGSCUSTOMITEM_LAUNCHREGSETTINGSVIEW_ENTRY 0x8a005e
#define SETTINGSCUSTOMITEM_LAUNCHREGSETTINGSVIEW_EXIT 0x8a005f
#define SETTINGSCUSTOMITEM_SELECTEDACTION_ENTRY 0x8a0060
#define SETTINGSCUSTOMITEM_SELECTEDACTION_EXIT 0x8a0061
#define SETTINGSCUSTOMITEM_WORKDAYSSETTING_ENTRY 0x8a0062
#define SETTINGSCUSTOMITEM_WORKDAYSSETTING_EXIT 0x8a0063


#endif

// End of file

