// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENREGIONALINFODATATRACES_H__
#define __CALENREGIONALINFODATATRACES_H__

#define KOstTraceComponentID 0x2002ea3c

#define CALENREGIONALINFO_CALENREGIONALINFO_ENTRY 0x8a0020
#define CALENREGIONALINFO_CALENREGIONALINFO_EXIT 0x8a0021
#define DUP1_CALENREGIONALINFO_CALENREGIONALINFO_ENTRY 0x8a0022
#define DUP1_CALENREGIONALINFO_CALENREGIONALINFO_EXIT 0x8a0023
#define CALENREGIONALINFO_SHOWREGIONALDETAILS_ENTRY 0x8a0024
#define CALENREGIONALINFO_SHOWREGIONALDETAILS_EXIT 0x8a0025


#endif

// End of file

