// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENLUNARCHINESEPLUGINPROXYTRACES_H__
#define __CALENLUNARCHINESEPLUGINPROXYTRACES_H__

#define KOstTraceComponentID 0x2002ea3c

#define _IMPLEMENTATIONGROUPPROXY_ENTRY 0x8a001e
#define _IMPLEMENTATIONGROUPPROXY_EXIT 0x8a001f


#endif

// End of file

