#ifndef GLXZOOMWIDGET_GLOBAL_H
#define GLXZOOMWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GLXZOOMWIDGET_LIBRARY)
#  define GLXZOOMWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GLXZOOMWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GLXZOOMWIDGET_GLOBAL_H
