// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __DATETIMESETTINGSPLUGINTRACES_H__
#define __DATETIMESETTINGSPLUGINTRACES_H__

#define KOstTraceComponentID 0x102818e9

#define DATETIMESETTINGSPLUGIN_DATETIMESETTINGSPLUGIN_ENTRY 0x8a0001
#define DATETIMESETTINGSPLUGIN_DATETIMESETTINGSPLUGIN_EXIT 0x8a0002
#define DUP1_DATETIMESETTINGSPLUGIN_DATETIMESETTINGSPLUGIN_ENTRY 0x8a0003
#define DUP1_DATETIMESETTINGSPLUGIN_DATETIMESETTINGSPLUGIN_EXIT 0x8a0004
#define DATETIMESETTINGSPLUGIN_UID_ENTRY 0x8a0005
#define DATETIMESETTINGSPLUGIN_UID_EXIT 0x8a0006
#define DATETIMESETTINGSPLUGIN_CREATESETTINGFORMITEMDATA_ENTRY 0x8a0007
#define DATETIMESETTINGSPLUGIN_CREATESETTINGFORMITEMDATA_EXIT 0x8a0008


#endif

// End of file

