// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CLOCKAPPCONTROLLERTRACES_H__
#define __CLOCKAPPCONTROLLERTRACES_H__

#define KOstTraceComponentID 0x2002bce3

#define CLOCKAPPCONTROLLER_CLOCKAPPCONTROLLER_ENTRY 0x8a0001
#define CLOCKAPPCONTROLLER_CLOCKAPPCONTROLLER_EXIT 0x8a0002
#define DUP1_CLOCKAPPCONTROLLER_CLOCKAPPCONTROLLER_ENTRY 0x8a0003
#define DUP1_CLOCKAPPCONTROLLER_CLOCKAPPCONTROLLER_EXIT 0x8a0004
#define CLOCKAPPCONTROLLER_HANDLEAPPREADY_ENTRY 0x8a0005
#define CLOCKAPPCONTROLLER_HANDLEAPPREADY_EXIT 0x8a0006


#endif

// End of file

