TEMPLATE = subdirs
SUBDIRS = 


# DO NOT auto-generate any deployment files

# Generate the rom iby file and the maemo debian install file
# from the template.pkg files already generated by qmake
#symbian {
#	exists( $$PWD/../../../../brtools/platform/symbian/install/generate-rom-iby.bat ) {
#		system($$PWD/../../../../brtools/platform/symbian/install/generate-rom-iby.bat)
#	}
#	exists( $$PWD/../../../../brtools/platform/maemo/generate-debian-files.bat ) {
#		system($$PWD/../../../../brtools/platform/maemo/generate-debian-files.bat)
#	}
#}
