// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENLUNARINFOTRACES_H__
#define __CALENLUNARINFOTRACES_H__

#define KOstTraceComponentID 0x20022edb

#define TCALENLUNARINFO_HASFESTIVAL_ENTRY 0x8a0013
#define TCALENLUNARINFO_HASFESTIVAL_EXIT 0x8a0014
#define TCALENLUNARINFO_HASSOLARTERM_ENTRY 0x8a0015
#define TCALENLUNARINFO_HASSOLARTERM_EXIT 0x8a0016
#define TCALENLUNARINFO_ANIMALYEAR_ENTRY 0x8a0017


#endif

// End of file

