// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CLOCKCITYLISTPROXYMODELTRACES_H__
#define __CLOCKCITYLISTPROXYMODELTRACES_H__

#define KOstTraceComponentID 0xabcde123

#define CLOCKCITYLISTPROXYMODEL_CLOCKCITYLISTPROXYMODEL_ENTRY 0x8a0001
#define CLOCKCITYLISTPROXYMODEL_CLOCKCITYLISTPROXYMODEL_EXIT 0x8a0002
#define CLOCKCITYLISTPROXYMODEL_FILTERACCEPTSROW_ENTRY 0x8a0003
#define CLOCKCITYLISTPROXYMODEL_FILTERACCEPTSROW_EXIT 0x8a0004
#define DUP1_CLOCKCITYLISTPROXYMODEL_FILTERACCEPTSROW_EXIT 0x8a0005


#endif

// End of file

