/*
* Copyright (c) 2010 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  Harvester message plugin
*
*/
// Created by TraceCompiler 2.3.0
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CMESSAGEDATAHANDLERTRACES_H__
#define __CMESSAGEDATAHANDLERTRACES_H__

#define KOstTraceComponentID 0x2001f701

#define CMESSAGEDATAHANDLER_NEWL_ENTRY 0x8a0001
#define CMESSAGEDATAHANDLER_NEWL_EXIT 0x8a0002
#define CMESSAGEDATAHANDLER_ISVALIDMESSAGETYPE_ENTRY 0x8a0003
#define CMESSAGEDATAHANDLER_ISVALIDMESSAGETYPE_EXIT 0x8a0004
#define CMESSAGEDATAHANDLER_HANDLENEXTREQUEST_ENTRY 0x8a001b
#define CMESSAGEDATAHANDLER_HANDLENEXTREQUEST_EXIT 0x8a001c
#define CMESSAGEDATAHANDLER_RESUMEL_ENTRY 0x8a001d
#define CMESSAGEDATAHANDLER_RESUMEL_EXIT 0x8a001e
#define CMESSAGEDATAHANDLER_CONSTRUCTL 0x860001
#define DUP1_CMESSAGEDATAHANDLER_CONSTRUCTL 0x860002
#define CMESSAGEDATAHANDLER_ISVALIDMESSAGETYPE 0x860003
#define DUP1_CMESSAGEDATAHANDLER_ISVALIDMESSAGETYPE 0x860004
#define CMESSAGEDATAHANDLER_CREATEMESSAGEINDEXITEML 0x860005
#define DUP1_CMESSAGEDATAHANDLER_CREATEMESSAGEINDEXITEML 0x860006
#define DUP2_CMESSAGEDATAHANDLER_CREATEMESSAGEINDEXITEML 0x860007
#define DUP3_CMESSAGEDATAHANDLER_CREATEMESSAGEINDEXITEML 0x860008
#define DUP4_CMESSAGEDATAHANDLER_CREATEMESSAGEINDEXITEML 0x860009
#define DUP7_CMESSAGEDATAHANDLER_CREATEMESSAGEINDEXITEML 0x86000c
#define DUP9_CMESSAGEDATAHANDLER_CREATEMESSAGEINDEXITEML 0x86000e
#define DUP14_CMESSAGEDATAHANDLER_CREATEMESSAGEINDEXITEML 0x860013
#define CMESSAGEDATAHANDLER_RUNL 0x860014
#define CMESSAGEDATAHANDLER_RUNERROR 0x860015
#define DUP5_CMESSAGEDATAHANDLER_CREATEMESSAGEINDEXITEML 0x86002e


#endif

// End of file

