/*
* Copyright (c) 2010 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  
*
*/
// Created by TraceCompiler 2.3.0
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CMESSAGEPLUGINTRACES_H__
#define __CMESSAGEPLUGINTRACES_H__

#define KOstTraceComponentID 0x2001f701

#define CMESSAGEPLUGIN_STARTHARVESTINGL_ENTRY 0x8a000f
#define CMESSAGEPLUGIN_STARTHARVESTINGL_EXIT 0x8a0010
#define CMESSAGEPLUGIN_MOUNTL_ENTRY 0x8a0011
#define CMESSAGEPLUGIN_MOUNTL_EXIT 0x8a0012
#define CMESSAGEPLUGIN_UNMOUNT_ENTRY 0x8a0013
#define CMESSAGEPLUGIN_UNMOUNT_EXIT 0x8a0014
#define CMESSAGEPLUGIN_DATABASEPATHLC_ENTRY 0x8a0015
#define CMESSAGEPLUGIN_DATABASEPATHLC_EXIT 0x8a0016
#define CMESSAGEPLUGIN_HANDLESESSIONEVENTL_ENTRY 0x8a0017
#define CMESSAGEPLUGIN_HANDLESESSIONEVENTL_EXIT 0x8a0018
#define CMESSAGEPLUGIN_CALCULATEMESSAGETYPE_ENTRY 0x8a0019
#define CMESSAGEPLUGIN_CALCULATEMESSAGETYPE_EXIT 0x8a001a
#define CMESSAGEPLUGIN_PAUSEPLUGINL_ENTRY 0x8a0025
#define CMESSAGEPLUGIN_PAUSEPLUGINL_EXIT 0x8a0026
#define CMESSAGEPLUGIN_RESUMEPLUGINL_ENTRY 0x8a0027
#define CMESSAGEPLUGIN_RESUMEPLUGINL_EXIT 0x8a0028
#define CMESSAGEPLUGIN_MOUNTAVAILABLEDRIVESINQUEUE_ENTRY 0x8a0029
#define CMESSAGEPLUGIN_MOUNTAVAILABLEDRIVESINQUEUE_EXIT 0x8a002a
#define CMESSAGEPLUGIN_CONSTRUCTL 0x86001f
#define CMESSAGEPLUGIN_STARTPLUGINL 0x860020
#define CMESSAGEPLUGIN_MOUNTL 0x860021
#define CMESSAGEPLUGIN_HANDLESESSIONEVENTL 0x860022
#define DUP1_CMESSAGEPLUGIN_HANDLESESSIONEVENTL 0x860023
#define DUP2_CMESSAGEPLUGIN_HANDLESESSIONEVENTL 0x860024
#define DUP3_CMESSAGEPLUGIN_HANDLESESSIONEVENTL 0x860025
#define CMESSAGEPLUGIN_CALCULATEMESSAGETYPE 0x860026
#define DUP1_CMESSAGEPLUGIN_CALCULATEMESSAGETYPE 0x860027
#define DUP5_CMESSAGEPLUGIN_CALCULATEMESSAGETYPE 0x86002b
#define DUP6_CMESSAGEPLUGIN_CALCULATEMESSAGETYPE 0x86002c
#define DUP7_CMESSAGEPLUGIN_CALCULATEMESSAGETYPE 0x86002d


#endif

// End of file

