/*
* Copyright (c) 2010 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  
*
*/
// Created by TraceCompiler 2.3.0
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CMESSAGEMONITORTRACES_H__
#define __CMESSAGEMONITORTRACES_H__

#define KOstTraceComponentID 0x2001f701

#define CMESSAGEMONITOR_CMESSAGEMONITOR_ENTRY 0x8a0005
#define CMESSAGEMONITOR_CMESSAGEMONITOR_EXIT 0x8a0006
#define CMESSAGEMONITOR_CONSTRUCTL_ENTRY 0x8a0007
#define CMESSAGEMONITOR_CONSTRUCTL_EXIT 0x8a0008
#define CMESSAGEMONITOR_HANDLEMSGMOVEDL_ENTRY 0x8a0009
#define CMESSAGEMONITOR_HANDLEMSGMOVEDL_EXIT 0x8a000a
#define CMESSAGEMONITOR_HANDLEMSGCREATEDCHANGEDL_ENTRY 0x8a000b
#define CMESSAGEMONITOR_HANDLEMSGCREATEDCHANGEDL_EXIT 0x8a000c
#define CMESSAGEMONITOR_HANDLEMSGDELETEDL_ENTRY 0x8a000d
#define CMESSAGEMONITOR_HANDLEMSGDELETEDL_EXIT 0x8a000e
#define CMESSAGEMONITOR_RESUMEL_ENTRY 0x8a0023
#define CMESSAGEMONITOR_RESUMEL_EXIT 0x8a0024
#define CMESSAGEMONITOR_HANDLEMSGMOVEDL 0x860016
#define CMESSAGEMONITOR_HANDLEMSGCREATEDCHANGEDL 0x860017
#define DUP1_CMESSAGEMONITOR_HANDLEMSGCREATEDCHANGEDL 0x860018
#define DUP2_CMESSAGEMONITOR_HANDLEMSGCREATEDCHANGEDL 0x860019
#define DUP4_CMESSAGEMONITOR_HANDLEMSGCREATEDCHANGEDL 0x86001a
#define DUP5_CMESSAGEMONITOR_HANDLEMSGCREATEDCHANGEDL 0x86001b
#define DUP6_CMESSAGEMONITOR_HANDLEMSGCREATEDCHANGEDL 0x86001c
#define DUP7_CMESSAGEMONITOR_HANDLEMSGCREATEDCHANGEDL 0x86001d
#define CMESSAGEMONITOR_HANDLEMSGDELETEDL 0x86001e


#endif

// End of file

