// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENDELETINGSTATETRACES_H__
#define __CALENDELETINGSTATETRACES_H__

#define KOstTraceComponentID 0x10282f25

#define CCALENDELETINGSTATE_NEWLC_ENTRY 0x8a00a0
#define CCALENDELETINGSTATE_NEWLC_EXIT 0x8a00a1
#define CCALENDELETINGSTATE_CONSTRUCTL_ENTRY 0x8a00a2
#define CCALENDELETINGSTATE_CONSTRUCTL_EXIT 0x8a00a3
#define CCALENDELETINGSTATE_CCALENDELETINGSTATE_ENTRY 0x8a00a4
#define CCALENDELETINGSTATE_CCALENDELETINGSTATE_EXIT 0x8a00a5
#define DUP1_CCALENDELETINGSTATE_CCALENDELETINGSTATE_ENTRY 0x8a00a6
#define DUP1_CCALENDELETINGSTATE_CCALENDELETINGSTATE_EXIT 0x8a00a7
#define CCALENDELETINGSTATE_HANDLECOMMANDL_ENTRY 0x8a00a8
#define CCALENDELETINGSTATE_HANDLECOMMANDL_EXIT 0x8a00a9
#define CCALENDELETINGSTATE_HANDLENOTIFICATIONL_ENTRY 0x8a00aa
#define CCALENDELETINGSTATE_HANDLENOTIFICATIONL_EXIT 0x8a00ab


#endif

// End of file

