// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENIDLESTATETRACES_H__
#define __CALENIDLESTATETRACES_H__

#define KOstTraceComponentID 0x10282f25

#define CCALENIDLESTATE_NEWLC_ENTRY 0x8a00f2
#define CCALENIDLESTATE_NEWLC_EXIT 0x8a00f3
#define CCALENIDLESTATE_CONSTRUCTL_ENTRY 0x8a00f4
#define CCALENIDLESTATE_CONSTRUCTL_EXIT 0x8a00f5
#define CCALENIDLESTATE_CCALENIDLESTATE_ENTRY 0x8a00f6
#define CCALENIDLESTATE_CCALENIDLESTATE_EXIT 0x8a00f7
#define DUP1_CCALENIDLESTATE_CCALENIDLESTATE_ENTRY 0x8a00f8
#define DUP1_CCALENIDLESTATE_CCALENIDLESTATE_EXIT 0x8a00f9
#define CCALENIDLESTATE_HANDLECOMMANDL_ENTRY 0x8a00fa
#define CCALENIDLESTATE_HANDLECOMMANDL_EXIT 0x8a00fb
#define CCALENIDLESTATE_HANDLENOTIFICATIONL_ENTRY 0x8a00fc
#define CCALENIDLESTATE_HANDLENOTIFICATIONL_EXIT 0x8a00fd


#endif

// End of file

