// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENEXITINGSTATETRACES_H__
#define __CALENEXITINGSTATETRACES_H__

#define KOstTraceComponentID 0x10282f25

#define CCALENEXITINGSTATE_NEWLC_ENTRY 0x8a00da
#define CCALENEXITINGSTATE_NEWLC_EXIT 0x8a00db
#define CCALENEXITINGSTATE_CONSTRUCTL_ENTRY 0x8a00dc
#define CCALENEXITINGSTATE_CONSTRUCTL_EXIT 0x8a00dd
#define CCALENEXITINGSTATE_CCALENEXITINGSTATE_ENTRY 0x8a00de
#define CCALENEXITINGSTATE_CCALENEXITINGSTATE_EXIT 0x8a00df
#define DUP1_CCALENEXITINGSTATE_CCALENEXITINGSTATE_ENTRY 0x8a00e0
#define DUP1_CCALENEXITINGSTATE_CCALENEXITINGSTATE_EXIT 0x8a00e1
#define CCALENEXITINGSTATE_HANDLECOMMANDL_ENTRY 0x8a00e2
#define CCALENEXITINGSTATE_HANDLECOMMANDL_EXIT 0x8a00e3
#define CCALENEXITINGSTATE_HANDLENOTIFICATIONL_ENTRY 0x8a00e4
#define CCALENEXITINGSTATE_HANDLENOTIFICATIONL_EXIT 0x8a00e5


#endif

// End of file

