// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENASYNCCALLBACKTRACES_H__
#define __CALENASYNCCALLBACKTRACES_H__

#define KOstTraceComponentID 0x10282f25

#define CALENASYNCCALLBACK_CALENASYNCCALLBACK_ENTRY 0x8a0011
#define CALENASYNCCALLBACK_CALENASYNCCALLBACK_EXIT 0x8a0012
#define CALENASYNCCALLBACK_NEWL_ENTRY 0x8a0013
#define CALENASYNCCALLBACK_NEWL_EXIT 0x8a0014
#define DUP1_CALENASYNCCALLBACK_CALENASYNCCALLBACK_ENTRY 0x8a0015
#define DUP1_CALENASYNCCALLBACK_CALENASYNCCALLBACK_EXIT 0x8a0016
#define CALENASYNCCALLBACK_BASECONSTRUCTL_ENTRY 0x8a0017
#define CALENASYNCCALLBACK_BASECONSTRUCTL_EXIT 0x8a0018
#define CALENASYNCCALLBACK_RUNL_ENTRY 0x8a0019
#define CALENASYNCCALLBACK_RUNL_EXIT 0x8a001a


#endif

// End of file

