// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENACTIONUITRACES_H__
#define __CALENACTIONUITRACES_H__

#define KOstTraceComponentID 0x10282f25

#define CCALENACTIONUI_NEWL_ENTRY 0x8a0001
#define CCALENACTIONUI_NEWL_EXIT 0x8a0002
#define CCALENACTIONUI_CCALENACTIONUI_ENTRY 0x8a0003
#define CCALENACTIONUI_CCALENACTIONUI_EXIT 0x8a0004
#define CCALENACTIONUI_CONSTRUCTL_ENTRY 0x8a0005
#define CCALENACTIONUI_CONSTRUCTL_EXIT 0x8a0006
#define DUP1_CCALENACTIONUI_CCALENACTIONUI_ENTRY 0x8a0007
#define DUP1_CCALENACTIONUI_CCALENACTIONUI_EXIT 0x8a0008
#define CCALENACTIONUI_GETCOMMANDHANDLERL_ENTRY 0x8a0009
#define CCALENACTIONUI_GETCOMMANDHANDLERL_EXIT 0x8a000a
#define CCALENACTIONUI_HANDLECOMMANDL_ENTRY 0x8a000b
#define CCALENACTIONUI_HANDLECOMMANDL_EXIT 0x8a000c


#endif

// End of file

