// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENSENDINGSTATETRACES_H__
#define __CALENSENDINGSTATETRACES_H__

#define KOstTraceComponentID 0x10282f25

#define CCALENSENDINGSTATE_NEWLC_ENTRY 0x8a0131
#define CCALENSENDINGSTATE_NEWLC_EXIT 0x8a0132
#define CCALENSENDINGSTATE_CONSTRUCTL_ENTRY 0x8a0133
#define CCALENSENDINGSTATE_CONSTRUCTL_EXIT 0x8a0134
#define CCALENSENDINGSTATE_CCALENSENDINGSTATE_ENTRY 0x8a0135
#define CCALENSENDINGSTATE_CCALENSENDINGSTATE_EXIT 0x8a0136
#define DUP1_CCALENSENDINGSTATE_CCALENSENDINGSTATE_ENTRY 0x8a0137
#define DUP1_CCALENSENDINGSTATE_CCALENSENDINGSTATE_EXIT 0x8a0138
#define CCALENSENDINGSTATE_HANDLECOMMANDL_ENTRY 0x8a0139
#define CCALENSENDINGSTATE_HANDLECOMMANDL_EXIT 0x8a013a
#define CCALENSENDINGSTATE_HANDLENOTIFICATIONL_ENTRY 0x8a013b
#define CCALENSENDINGSTATE_HANDLENOTIFICATIONL_EXIT 0x8a013c


#endif

// End of file

