// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENEDITUITRACES_H__
#define __CALENEDITUITRACES_H__

#define KOstTraceComponentID 0x10282f25

#define CCALENEDITUI_NEWL_ENTRY 0x8a00ca
#define CCALENEDITUI_NEWL_EXIT 0x8a00cb
#define CCALENEDITUI_CCALENEDITUI_ENTRY 0x8a00cc
#define CCALENEDITUI_CCALENEDITUI_EXIT 0x8a00cd
#define DUP1_CCALENEDITUI_CCALENEDITUI_ENTRY 0x8a00ce
#define DUP1_CCALENEDITUI_CCALENEDITUI_EXIT 0x8a00cf
#define CCALENEDITUI_CONSTRUCTL_ENTRY 0x8a00d0
#define CCALENEDITUI_CONSTRUCTL_EXIT 0x8a00d1
#define CCALENEDITUI_HANDLECOMMANDL_ENTRY 0x8a00d2
#define CCALENEDITUI_HANDLECOMMANDL_EXIT 0x8a00d3
#define CCALENEDITUI_HANDLEENTRYSAVED_ENTRY 0x8a00d4
#define CCALENEDITUI_HANDLEENTRYSAVED_EXIT 0x8a00d5
#define CCALENEDITUI_HANDLEDIALOGCLOSED_ENTRY 0x8a00d6
#define CCALENEDITUI_HANDLEDIALOGCLOSED_EXIT 0x8a00d7
#define CCALENEDITUI_HANDLENOTIFICATION_ENTRY 0x8a00d8
#define CCALENEDITUI_HANDLENOTIFICATION_EXIT 0x8a00d9


#endif

// End of file

