// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENEDITINGSTATETRACES_H__
#define __CALENEDITINGSTATETRACES_H__

#define KOstTraceComponentID 0x10282f25

#define CCALENEDITINGSTATE_NEWLC_ENTRY 0x8a00be
#define CCALENEDITINGSTATE_NEWLC_EXIT 0x8a00bf
#define CCALENEDITINGSTATE_CONSTRUCTL_ENTRY 0x8a00c0
#define CCALENEDITINGSTATE_CONSTRUCTL_EXIT 0x8a00c1
#define CCALENEDITINGSTATE_CCALENEDITINGSTATE_ENTRY 0x8a00c2
#define CCALENEDITINGSTATE_CCALENEDITINGSTATE_EXIT 0x8a00c3
#define DUP1_CCALENEDITINGSTATE_CCALENEDITINGSTATE_ENTRY 0x8a00c4
#define DUP1_CCALENEDITINGSTATE_CCALENEDITINGSTATE_EXIT 0x8a00c5
#define CCALENEDITINGSTATE_HANDLECOMMANDL_ENTRY 0x8a00c6
#define CCALENEDITINGSTATE_HANDLECOMMANDL_EXIT 0x8a00c7
#define CCALENEDITINGSTATE_HANDLENOTIFICATIONL_ENTRY 0x8a00c8
#define CCALENEDITINGSTATE_HANDLENOTIFICATIONL_EXIT 0x8a00c9


#endif

// End of file

