// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENPRINTINGSTATETRACES_H__
#define __CALENPRINTINGSTATETRACES_H__

#define KOstTraceComponentID 0x10282f25

#define CCALENPRINTINGSTATE_NEWLC_ENTRY 0x8a0125
#define CCALENPRINTINGSTATE_NEWLC_EXIT 0x8a0126
#define CCALENPRINTINGSTATE_CONSTRUCTL_ENTRY 0x8a0127
#define CCALENPRINTINGSTATE_CONSTRUCTL_EXIT 0x8a0128
#define CCALENPRINTINGSTATE_CCALENPRINTINGSTATE_ENTRY 0x8a0129
#define CCALENPRINTINGSTATE_CCALENPRINTINGSTATE_EXIT 0x8a012a
#define DUP1_CCALENPRINTINGSTATE_CCALENPRINTINGSTATE_ENTRY 0x8a012b
#define DUP1_CCALENPRINTINGSTATE_CCALENPRINTINGSTATE_EXIT 0x8a012c
#define CCALENPRINTINGSTATE_HANDLECOMMANDL_ENTRY 0x8a012d
#define CCALENPRINTINGSTATE_HANDLECOMMANDL_EXIT 0x8a012e
#define CCALENPRINTINGSTATE_HANDLENOTIFICATIONL_ENTRY 0x8a012f
#define CCALENPRINTINGSTATE_HANDLENOTIFICATIONL_EXIT 0x8a0130


#endif

// End of file

