// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENACTIONUIUTILSTRACES_H__
#define __CALENACTIONUIUTILSTRACES_H__

#define KOstTraceComponentID 0x10282f25

#define CALENACTIONUIUTILS_FINDPOSSIBLEINSTANCEL_ENTRY 0x8a000d
#define CALENACTIONUIUTILS_FINDPOSSIBLEINSTANCEL_EXIT 0x8a000e
#define CALENACTIONUIUTILS_SETTODOCOMPLETESTATUS_ENTRY 0x8a000f
#define CALENACTIONUIUTILS_SETTODOCOMPLETESTATUS_EXIT 0x8a0010


#endif

// End of file

