// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENHELPSTATETRACES_H__
#define __CALENHELPSTATETRACES_H__

#define KOstTraceComponentID 0x10282f25

#define CCALENHELPSTATE_NEWLC_ENTRY 0x8a00e6
#define CCALENHELPSTATE_NEWLC_EXIT 0x8a00e7
#define CCALENHELPSTATE_CONSTRUCTL_ENTRY 0x8a00e8
#define CCALENHELPSTATE_CONSTRUCTL_EXIT 0x8a00e9
#define CCALENHELPSTATE_CCALENHELPSTATE_ENTRY 0x8a00ea
#define CCALENHELPSTATE_CCALENHELPSTATE_EXIT 0x8a00eb
#define DUP1_CCALENHELPSTATE_CCALENHELPSTATE_ENTRY 0x8a00ec
#define DUP1_CCALENHELPSTATE_CCALENHELPSTATE_EXIT 0x8a00ed
#define CCALENHELPSTATE_HANDLECOMMANDL_ENTRY 0x8a00ee
#define CCALENHELPSTATE_HANDLECOMMANDL_EXIT 0x8a00ef
#define CCALENHELPSTATE_HANDLENOTIFICATIONL_ENTRY 0x8a00f0
#define CCALENHELPSTATE_HANDLENOTIFICATIONL_EXIT 0x8a00f1


#endif

// End of file

