/*
* Copyright (c) 2010 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  
*
*/
// Created by TraceCompiler 2.3.0
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CFOLDERRENAMEDHARVESTERTRACES_H__
#define __CFOLDERRENAMEDHARVESTERTRACES_H__

#define KOstTraceComponentID 0x2001f703

#define CFOLDERRENAMEDHARVESTER_CFOLDERRENAMEDHARVESTER_ENTRY 0x8a0025
#define CFOLDERRENAMEDHARVESTER_CFOLDERRENAMEDHARVESTER_EXIT 0x8a0026
#define CFOLDERRENAMEDHARVESTER_STARTL_ENTRY 0x8a0027
#define CFOLDERRENAMEDHARVESTER_STARTL_EXIT 0x8a0028
#define CFOLDERRENAMEDHARVESTER_GETNEXTFOLDERL_ENTRY 0x8a0029
#define CFOLDERRENAMEDHARVESTER_GETNEXTFOLDERL_EXIT 0x8a002a
#define CFOLDERRENAMEDHARVESTER_GETFILEIDL_ENTRY 0x8a002b
#define CFOLDERRENAMEDHARVESTER_GETFILEIDL_EXIT 0x8a002c
#define CFOLDERRENAMEDHARVESTER_RUNL_ENTRY 0x8a002d
#define CFOLDERRENAMEDHARVESTER_RUNL_EXIT 0x8a002e
#define DUP1_CFOLDERRENAMEDHARVESTER_RUNL_EXIT 0x8a002f
#define CFOLDERRENAMEDHARVESTER_HANDLEFOLDERRENAMEL_ENTRY 0x8a0050
#define CFOLDERRENAMEDHARVESTER_HANDLEFOLDERRENAMEL_EXIT 0x8a0051
#define CFOLDERRENAMEDHARVESTER_GETNEXTFOLDERL 0x86003c
#define DUP1_CFOLDERRENAMEDHARVESTER_GETNEXTFOLDERL 0x86003d
#define CFOLDERRENAMEDHARVESTER_DOCANCEL 0x86003e
#define CFOLDERRENAMEDHARVESTER_RUNERROR 0x86003f
#define CFOLDERRENAMEDHARVESTER_SETNEXTREQUEST 0x860040


#endif

// End of file

