/*
* Copyright (c) 2005 - 2010 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  Macro definition file for logging.
*
*/

// Autogenerated from .\phoneloggerviewcommands.st by the stringtable tool - Do not edit

#ifndef STRINGTABLE_PhoneLoggerviewCommands
#define STRINGTABLE_PhoneLoggerviewCommands

#include <stringpool.h>

struct TStringTable;

/** A String table */
class PhoneLoggerviewCommands 
	{
public:
	enum TStrings
		{
		/** EPhoneViewStartValue */
		EPhoneViewStartValue,
		/** EPhoneViewRemoveNumberEntry */
		EPhoneViewRemoveNumberEntry,
		/** EPhoneViewSetNumberEntryVisible */
		EPhoneViewSetNumberEntryVisible,
		/** EPhoneViewGetNumberFromEntry */
		EPhoneViewGetNumberFromEntry,
		/** EPhoneViewGetNumberEntryCount */
		EPhoneViewGetNumberEntryCount,
		/** EPhoneViewGetNumberEntryIsUsedStatus */
		EPhoneViewGetNumberEntryIsUsedStatus,
		/** EPhoneViewGetNumberEntryIsVisibleStatus */
		EPhoneViewGetNumberEntryIsVisibleStatus,
		/** EPhoneViewClearNumberEntryContent */
		EPhoneViewClearNumberEntryContent,
		/** EPhoneViewCreateCallHeader */
		EPhoneViewCreateCallHeader,
		/** EPhoneViewCreateEmergencyCallHeader */
		EPhoneViewCreateEmergencyCallHeader,
		/** EPhoneViewUpdateCallHeaderCallDuration */
		EPhoneViewUpdateCallHeaderCallDuration,
		/** EPhoneViewRemoveCallHeader */
		EPhoneViewRemoveCallHeader,
		/** EPhoneViewUpdateCba */
		EPhoneViewUpdateCba,
		/** EPhoneViewUpdateBubble */
		EPhoneViewUpdateBubble,
		/** EPhoneViewActivateAudioPathUIChanges */
		EPhoneViewActivateAudioPathUIChanges,
		/** EPhoneViewActivateAudioAvailabilityUIChanges */
		EPhoneViewActivateAudioAvailabilityUIChanges,
		/** EPhoneViewActivateMuteUIChanges */
		EPhoneViewActivateMuteUIChanges,
		/** EPhoneViewShowNote */
		EPhoneViewShowNote,
		/** EPhoneViewShowGlobalNote */
		EPhoneViewShowGlobalNote,
		/** EPhoneViewShowProgressNote */
		EPhoneViewShowProgressNote,
		/** EPhoneViewRemoveNote */
		EPhoneViewRemoveNote,
		/** EPhoneViewRemoveProgressNote */
		EPhoneViewRemoveProgressNote,
		/** EPhoneViewRemoveGlobalNote */
		EPhoneViewRemoveGlobalNote,
		/** EPhoneViewShowQuery */
		EPhoneViewShowQuery,
		/** EPhoneViewSetListQueryString */
		EPhoneViewSetListQueryString,
		/** EPhoneViewRemoveQuery */
		EPhoneViewRemoveQuery,
		/** EPhoneViewBringAppToForeground */
		EPhoneViewBringAppToForeground,
		/** EPhoneViewSendToBackground */
		EPhoneViewSendToBackground,
		/** EPhoneViewGetTopApplicationIsDisplayedStatus */
		EPhoneViewGetTopApplicationIsDisplayedStatus,
		/** EPhoneViewGetForegroundApplication */
		EPhoneViewGetForegroundApplication,
		/** EPhoneViewStartCapturingKey */
		EPhoneViewStartCapturingKey,
		/** EPhoneViewStopCapturingKey */
		EPhoneViewStopCapturingKey,
		/** EPhoneViewSetGlobalNotifiersDisabled */
		EPhoneViewSetGlobalNotifiersDisabled,
		/** EPhoneViewOpenSingleItemFetchDialog */
		EPhoneViewOpenSingleItemFetchDialog,
		/** EPhoneViewRemovePhoneDialogs */
		EPhoneViewRemovePhoneDialogs,
		/** EPhoneViewCreateConference */
		EPhoneViewCreateConference,
		/** EPhoneViewAddToConference */
		EPhoneViewAddToConference,
		/** EPhoneViewRemoveFromConference */
		EPhoneViewRemoveFromConference,
		/** EPhoneViewPrivateFromConference */
		EPhoneViewPrivateFromConference,
		/** EPhoneViewSelectedConfMember */
		EPhoneViewSelectedConfMember,
		/** EPhoneViewGetCallIdByState */
		EPhoneViewGetCallIdByState,
		/** EPhoneViewGetCountOfActiveCalls */
		EPhoneViewGetCountOfActiveCalls,
		/** EPhoneViewSetNaviPaneAudioVolume */
		EPhoneViewSetNaviPaneAudioVolume,
		/** EPhoneViewHideNaviPaneAudioVolume */
		EPhoneViewHideNaviPaneAudioVolume,
		/** EPhoneViewGetIsConference */
		EPhoneViewGetIsConference,
		/** EPhoneViewGetCallExistsInConference */
		EPhoneViewGetCallExistsInConference,
		/** EPhoneViewRemoveAllCallHeaders */
		EPhoneViewRemoveAllCallHeaders,
		/** EPhoneViewPlayRingTone */
		EPhoneViewPlayRingTone,
		/** EPhoneViewMuteRingTone */
		EPhoneViewMuteRingTone,
		/** EPhoneViewStopRingTone */
		EPhoneViewStopRingTone,
		/** EPhoneViewMuteRingToneOnAnswer */
		EPhoneViewMuteRingToneOnAnswer,
		/** EPhoneViewCipheringInfoChange */
		EPhoneViewCipheringInfoChange,
		/** EPhoneViewCloseFSW */
		EPhoneViewCloseFSW,
		/** EPhoneViewLaunchRfsDeep */
		EPhoneViewLaunchRfsDeep,
		/** EPhoneViewLaunchRfsNormal */
		EPhoneViewLaunchRfsNormal,
		/** EPhoneViewOpenSoftRejectEditor */
		EPhoneViewOpenSoftRejectEditor,
		/** EPhoneViewSetSecurityMode */
		EPhoneViewSetSecurityMode,
		/** EPhoneViewGetSecurityModeStatus */
		EPhoneViewGetSecurityModeStatus,
		/** EPhoneViewEnableKeyLock */
		EPhoneViewEnableKeyLock,
		/** EPhoneViewEnableKeyLockWithoutNote */
		EPhoneViewEnableKeyLockWithoutNote,
		/** EPhoneViewUpdateFSW */
		EPhoneViewUpdateFSW,
		/** EPhoneViewBringIdleToForeground */
		EPhoneViewBringIdleToForeground,
		/** EPhoneViewBeginUpdate */
		EPhoneViewBeginUpdate,
		/** EPhoneViewEndUpdate */
		EPhoneViewEndUpdate,
		/** EPhoneViewRemoveConferenceBubble */
		EPhoneViewRemoveConferenceBubble,
		/** EPhoneViewSetTouchPaneButtons */
		EPhoneViewSetTouchPaneButtons,
		/** EPhoneViewOpenCallHandling */
		EPhoneViewOpenCallHandling,
		/** EPhoneViewGetAudioVolumeLevel */
		EPhoneViewGetAudioVolumeLevel,
		/** EPhoneViewRemoveDtmfNote */
		EPhoneViewRemoveDtmfNote,
		/** EPhoneViewCancelAllNotications */
		EPhoneViewCancelAllNotications,
		/** EPhoneViewDisableKeyLock */
		EPhoneViewDisableKeyLock,
		/** EPhoneViewSendAiwCommand */
		EPhoneViewSendAiwCommand,
		/** EPhoneViewCipheringInfoChangePlayTone */
		EPhoneViewCipheringInfoChangePlayTone,
		/** EPhoneViewRemoveGlobalWaitNote */
		EPhoneViewRemoveGlobalWaitNote,
		/** EPhoneViewSetPhoneCustomization */
		EPhoneViewSetPhoneCustomization,
		/** EPhoneViewSetViewCustomization */
		EPhoneViewSetViewCustomization,
		/** EPhoneViewSetButtonCustomization */
		EPhoneViewSetButtonCustomization,
		/** EPhoneViewUpdateContactByString */
		EPhoneViewUpdateContactByString,
		/** EPhoneViewAddContactByString */
		EPhoneViewAddContactByString,
		/** EPhoneViewEnableToolbarButton */
		EPhoneViewEnableToolbarButton,
		/** EPhoneViewHideToolbar */
		EPhoneViewHideToolbar,
		/** EPhoneViewShowToolbar */
		EPhoneViewShowToolbar,
		/** EPhoneViewGetExpandedBubbleCallId */
		EPhoneViewGetExpandedBubbleCallId,
		/** EPhoneViewOpenDialer */
		EPhoneViewOpenDialer,
		/** EPhoneSetConferenceExpanded */
		EPhoneSetConferenceExpanded,
		/** EPhoneAppShutDown */
		EPhoneAppShutDown,
		/** EPhoneViewBackButtonActive */
		EPhoneViewBackButtonActive,
		/** EPhoneViewHsToForegroundAfterCall */
		EPhoneViewHsToForegroundAfterCall,
		/** EPhoneViewOpenContacts */
		EPhoneViewOpenContacts,
		/** EPhoneViewSetIhfFlag */
		EPhoneViewSetIhfFlag,
		/** EPhoneViewSetMuteFlag */
		EPhoneViewSetMuteFlag,
		/** EPhoneViewLaunchLogs */
		EPhoneViewLaunchLogs,
		/** EPhoneViewSetBlueToothFlag */
		EPhoneViewSetBlueToothFlag,
		/** EPhoneViewSetBluetoothAvailableFlag */
		EPhoneViewSetBluetoothAvailableFlag,
		/** , // Don't remove this, this should always be the last in list. */
		EPhoneAmountOfCommands
		};
	static const TStringTable Table;	
	};

#endif // STRINGTABLE_PhoneLoggerviewCommands

