/*
* Copyright (c) 2005 - 2010 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  Macro definition file for logging.
*
*/

// Autogenerated from .\phonestatestrings.st by the stringtable tool - Do not edit

#ifndef STRINGTABLE_PhoneStateStrings
#define STRINGTABLE_PhoneStateStrings

#include <stringpool.h>

struct TStringTable;

/** A String table */
class PhoneStateStrings 
	{
public:
	enum TStrings
		{
		/** EPhoneStateNull */
		EPhoneStateNull,
		/** EPhoneStateStartup */
		EPhoneStateStartup,
		/** EPhoneStateIdle */
		EPhoneStateIdle,
		/** EPhoneStateCallSetup */
		EPhoneStateCallSetup,
		/** EPhoneStateSingle */
		EPhoneStateSingle,
		/** EPhoneStateIncoming */
		EPhoneStateIncoming,
		/** EPhoneStateEmergency */
		EPhoneStateEmergency
		};
	static const TStringTable Table;	
	};

#endif // STRINGTABLE_PhoneStateStrings

