/*
* Copyright (c) 2005 - 2010 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  Macro definition file for logging.
*
*/

// Autogenerated from .\phonestatestringsgsm.st by the stringtable tool - Do not edit

#ifndef STRINGTABLE_PhoneStateStringsGSM
#define STRINGTABLE_PhoneStateStringsGSM

#include <stringpool.h>

struct TStringTable;

/** A String table */
class PhoneStateStringsGSM 
	{
public:
	enum TStrings
		{
		// GSM States - start at KPhoneStateProtocolFirst
		/** EPhoneStateAlerting */
		EPhoneStateAlerting,
		/** EPhoneStateAlertingInSingle */
		EPhoneStateAlertingInSingle,
		/** EPhoneStateWaitingInSingle */
		EPhoneStateWaitingInSingle,
		/** EPhoneStateTwoSingles */
		EPhoneStateTwoSingles,
		/** EPhoneStateCallSetupInSingle */
		EPhoneStateCallSetupInSingle,
		/** EPhoneStateConference */
		EPhoneStateConference,
		/** EPhoneStateConferenceAndCallSetup */
		EPhoneStateConferenceAndCallSetup,
		/** EPhoneStateConferenceAndSingle */
		EPhoneStateConferenceAndSingle,
		/** EPhoneStateConferenceAndWaiting */
		EPhoneStateConferenceAndWaiting,
		/** EPhoneStateSingleAndCallSetupAndWaiting */
		EPhoneStateSingleAndCallSetupAndWaiting,
		/** EPhoneStateCallSetupAndWaiting */
		EPhoneStateCallSetupAndWaiting,
		/** EPhoneStateTwoSinglesAndWaiting */
		EPhoneStateTwoSinglesAndWaiting,
		/** EPhoneStateConferenceAndSingleAndWaiting */
		EPhoneStateConferenceAndSingleAndWaiting,
		/** EPhoneStateConferenceAndWaitingAndCallSetup */
		EPhoneStateConferenceAndWaitingAndCallSetup,
		/** EPhoneStateLastGSMState */
		EPhoneStateLastGSMState
		};
	static const TStringTable Table;	
	};

#endif // STRINGTABLE_PhoneStateStringsGSM

