/*
* Copyright (c) 2010 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: 
*
*/
// Created by TraceCompiler 2.2.4
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __ALARMALERTWIDGET_PTRACES_H__
#define __ALARMALERTWIDGET_PTRACES_H__

#define KOstTraceComponentID 0xe3ab5737

#define ALARMALERTDIALOGPRIVATE_ALARMALERTDIALOGPRIVATE_ENTRY 0x8a0017
#define ALARMALERTDIALOGPRIVATE_ALARMALERTDIALOGPRIVATE_EXIT 0x8a0018
#define DUP1_ALARMALERTDIALOGPRIVATE_ALARMALERTDIALOGPRIVATE_ENTRY 0x8a0019
#define DUP1_ALARMALERTDIALOGPRIVATE_ALARMALERTDIALOGPRIVATE_EXIT 0x8a001a
#define ALARMALERTDIALOGPRIVATE_SETDEVICEDIALOGPARAMETERS_ENTRY 0x8a001b
#define ALARMALERTDIALOGPRIVATE_SETDEVICEDIALOGPARAMETERS_EXIT 0x8a001c
#define ALARMALERTDIALOGPRIVATE_DEVICEDIALOGERROR_ENTRY 0x8a001d
#define ALARMALERTDIALOGPRIVATE_DEVICEDIALOGERROR_EXIT 0x8a001e
#define ALARMALERTDIALOGPRIVATE_CLOSEDEVICEDIALOG_ENTRY 0x8a001f
#define ALARMALERTDIALOGPRIVATE_CLOSEDEVICEDIALOG_EXIT 0x8a0020
#define ALARMALERTDIALOGPRIVATE_DEVICEDIALOGWIDGET_ENTRY 0x8a0021
#define ALARMALERTDIALOGPRIVATE_SHOWEVENT_ENTRY 0x8a0022
#define ALARMALERTDIALOGPRIVATE_SHOWEVENT_EXIT 0x8a0023
#define ALARMALERTDIALOGPRIVATE_HANDLEORIENTATIONCHANGE_ENTRY 0x8a0026
#define ALARMALERTDIALOGPRIVATE_HANDLEORIENTATIONCHANGE_EXIT 0x8a0027
#define ALARMALERTDIALOGPRIVATE_SNOOZED_ENTRY 0x8a0028
#define ALARMALERTDIALOGPRIVATE_SNOOZED_EXIT 0x8a0029
#define ALARMALERTDIALOGPRIVATE_SILENCED_ENTRY 0x8a002a
#define ALARMALERTDIALOGPRIVATE_SILENCED_EXIT 0x8a002b
#define ALARMALERTDIALOGPRIVATE_ABOUTTODISPLAY_ENTRY 0x8a002c
#define ALARMALERTDIALOGPRIVATE_ABOUTTODISPLAY_EXIT 0x8a002d
#define ALARMALERTDIALOGPRIVATE_DISMISSED_ENTRY 0x8a002e
#define ALARMALERTDIALOGPRIVATE_DISMISSED_EXIT 0x8a002f
#define ALARMALERTDIALOGPRIVATE_PARSEANDFETCHPARAMS_ENTRY 0x8a0030
#define ALARMALERTDIALOGPRIVATE_PARSEANDFETCHPARAMS_EXIT 0x8a0031
#define ALARMALERTDIALOGPRIVATE_SETUPNORMALUI_ENTRY 0x8a0032
#define ALARMALERTDIALOGPRIVATE_SETUPNORMALUI_EXIT 0x8a0033
#define DUP1_ALARMALERTDIALOGPRIVATE_SETUPNORMALUI_EXIT 0x8a0034
#define ALARMALERTDIALOGPRIVATE_HANDLECLOCKALARMS_ENTRY 0x8a0035
#define ALARMALERTDIALOGPRIVATE_HANDLECLOCKALARMS_EXIT 0x8a0036
#define ALARMALERTDIALOGPRIVATE_HANDLECALENDARALARMS_ENTRY 0x8a0037
#define ALARMALERTDIALOGPRIVATE_HANDLECALENDARALARMS_EXIT 0x8a0038
#define ALARMALERTDIALOGPRIVATE_HANDLETODOALARMS_ENTRY 0x8a0039
#define ALARMALERTDIALOGPRIVATE_HANDLETODOALARMS_EXIT 0x8a003a
#define ALARMALERTDIALOGPRIVATE_HIDEEVENT_ENTRY 0x8a003b
#define ALARMALERTDIALOGPRIVATE_HIDEEVENT_EXIT 0x8a003c


#endif

// End of file

