// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CLOCKAPPLICATIONTRACES_H__
#define __CLOCKAPPLICATIONTRACES_H__

#define KOstTraceComponentID 0x10005903

#define CLOCKAPPLICATION_CLOCKAPPLICATION_ENTRY 0x8a0001
#define CLOCKAPPLICATION_CLOCKAPPLICATION_EXIT 0x8a0002
#define DUP1_CLOCKAPPLICATION_CLOCKAPPLICATION_ENTRY 0x8a0003
#define DUP1_CLOCKAPPLICATION_CLOCKAPPLICATION_EXIT 0x8a0004
#define CLOCKAPPLICATION_CREATECONTROLLER_ENTRY 0x8a0005
#define CLOCKAPPLICATION_CREATECONTROLLER_EXIT 0x8a0006
#define CLOCKAPPLICATION_EXECUTION_ENTRY 0x8a0007
#define CLOCKAPPLICATION_EXECUTION_EXIT 0x8a0008
#define CLOCKAPPLICATION_HANDLEAPPREADY_ENTRY 0x8a0009
#define CLOCKAPPLICATION_HANDLEAPPREADY_EXIT 0x8a000a


#endif

// End of file

