// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __NOTESAPPCONTROLLERTRACES_H__
#define __NOTESAPPCONTROLLERTRACES_H__

#define KOstTraceComponentID 0x2002bcdb

#define NOTESAPPCONTROLLER_NOTESAPPCONTROLLER_ENTRY 0x8a0001
#define NOTESAPPCONTROLLER_NOTESAPPCONTROLLER_EXIT 0x8a0002
#define DUP1_NOTESAPPCONTROLLER_NOTESAPPCONTROLLER_ENTRY 0x8a0003
#define DUP1_NOTESAPPCONTROLLER_NOTESAPPCONTROLLER_EXIT 0x8a0004
#define NOTESAPPCONTROLLER_HANDLEAPPREADY_ENTRY 0x8a0005
#define NOTESAPPCONTROLLER_HANDLEAPPREADY_EXIT 0x8a0006


#endif

// End of file

