# Copyright (c) Symbian Software Ltd 2008. All rights reserved. 
!/** 
!An Example String Table
!@publishedAll
!@released
!*/
# XML String table
fstringtable SMILElements
#
# Standard SMIL Elements
#
Ea 		a
EAnchor 	anchor
EAnimate	animate
EAnimateColor	animateColor
EAnimateMotion	animateMotion
EAnimation	animation
EArea		area
EAudio		audio
EBody		body
EBrush		brush
ECustomAttributes customAttributes
ECustomTest	customTest
EExcl		excl
EHead		head
EImg		img
ELayout		layout
EMeta		meta
EMetadata	metadata
EPar		par
EParam		param
EPrefetch	prefetch
EpriorityClass  priorityClass
ERef		ref
ERegion		region
ERegPoint	regPoint	
ERootLayout	root-layout
ESeq		seq
ESmil		smil
ESwitch		switch
EText		text
ETextstream	textstream
ETopLayout	topLayout
ETransition	transition
ETransitionFilter transitionFilter
EVideo 		video
