# Copyright (c) Symbian Software Ltd 2008. All rights reserved.
!/** 
!An Example String Table
!@publishedAll
!@released
!*/ 
# XML String table
fstringtable SMILGenericElements
#
# Standard SMIL Elements & Generic Equivalent
#
EAnchorBase 	anchor anchorBase
EAnimationBase	animation media
EAreaBase	area anchorBase
EAudioBase	audio media
EImgBase	img media
EParBase	par timing
ERefBase	ref media
ESeqBase	seq timing
ETextBase	text media
ETextstreamBase	textstream media
EVideoBase 	video media
