# Copyright (c) Symbian Software Ltd 2008. All rights reserved.
!/** 
!An Example String Table
!@publishedAll
!@released
!*/ 
# XML String table
fstringtable SMILAttributes
#
# Standard SMIL Element, Attributes & Values
#
EAAccessKey		a accesskey
EAActuate		a actuate onLoad onRequest
EAAlt			a alt
EABegin			a begin
EAClass			a class
EADestinationLevel 	a destinationLevel
EADestinationPlaystate	a destinationPlaystate pause play stop
EADur			a dur
EAEnd			a end
EAExternal		a external false true
EAFill			a fill freeze hold remove transition
EAHref			a href
EAId			a id
EAMax			a max
EAMin			a min
EARepeatCount		a repeatCount
EARepeatDur		a repeatDur
EAShow			a show new pause replace
EASourceLevel		a sourceLevel
EASourcePlaystate	a sourcePlaystate pause play stop
EATabIndex		a tabindex
EATarget		a target
EATitle			a title
EAXMLLang		a xml:lang
EAnchorBaseAccessKey	anchorBase accesskey
EAnchorBaseActuate	anchorBase actuate onLoad onRequest
EAnchorBaseAlt		anchorBase alt
EAnchorBaseBegin	anchorBase begin
EAnchorBaseClass	anchorBase class
EAnchorBaseCoOrds	anchorBase coords
EAnchorBaseDestLevel	anchorBase destinationLevel
EAnchorBaseDestinationPlaystate	anchorBase destinationPlaystate pause play stop
EAnchorBaseDur		anchorBase dur
EAnchorBaseEnd		anchorBase end
EAnchorBaseEndsync	anchorBase endsync
EAnchorBaseExternal	anchorBase external false true
EAnchorBaseFill		anchorBase fill hold freeze remove transition
EAnchorBaseHRef		anchorBase href
EAnchorBaseId		anchorBase id
EAnchorBaseMax		anchorBase max
EAnchorBaseMin		anchorBase min
EAnchorBase		anchorBase nohref nohref
EAnchorBaseRepeat	anchorBase repeat
EAnchorBaseRepeatCnt	anchorBase repeatCount
EAnchorBaseRepeatDur	anchorBase repeatDur
EAnchorBaseShape	anchorBase shape circle default poly rect
EAnchorBaseShow		anchorBase show new pause replace
EAnchorBaseSkipContent	anchorBase skip-content false true
EAnchorBaseSourceLev	anchorBase sourceLevel
EAnchorBaseSourcePlaystate	anchorBase sourcePlaystate pause play stop
EAnchorBaseTabIndex	anchorBase tabindex
EAnchorBaseTarget	anchorBase target
EAnchorBaseTitle	anchorBase title
EAnchorBaseXMLLang	anchorBase xml:lang
EBodyClass		body class
EBodyId			body id
EBodyTitle		body title
EBodyXMLLang		body xml:lang
EHeadClass		head class
EHeadId			head id
EHeadTitle		head title
EHeadXMLLang		head xml:lang
ELayoutClass		layout class
ELayoutId		layout id
ELayoutSysAudioDesc	layout systemAudioDesc off on
ELayoutSysBitrate	layout systemBitrate
ELayoutSysCPU		layout systemCPU
ELayoutSysCaptions	layout systemCaptions off on
ELayoutSysComp		layout systemComponent
ELayoutSysLang		layout systemLanguage
ELayoutSysOS		layout systemOperatingSystem
ELayoutSysOverCap	layout systemOverdubOrSubtitle overdub subtitle
ELayoutSysReq		layout systemRequired
ELayoutSysScrnDepth	layout systemScreenDepth
ELayoutSysScrnSize	layout systemScreenSize
ELayoutTitle		layout title
ElayoutType		layout type
ELayoutXMLLang		layout xml:lang
EMediaAbstract		media abstract
EMediaAlt		media alt
EMediaAuthor		media author
EMediaBegin		media begin
EMediaClass		media class
EMediaClipHypBegin	media clip-begin
EMediaClipHypEnd	media clip-end
EMediaClipBegin		media clipBegin
EMediaClipEnd		media clipEnd
EMediaCopyright		media copyright
EMediaCustomTest	media customTest
EMediaDur		media dur
EMediaEnd		media end
EMediaEndsync		media endsync
EMediaFill		media fill freeze hold remove transition
EMediaId		media id
EMediaLongDesc		media longdesc
EMediaMax		media max
EMediaMin		media min
EMediaReadIndex		media readIndex
EMediaRegion		media region
EMediaRepeat		media repeat
EMediaRepeatCount	media repeatCount
EMediaRepeatDur		media repeatDur
EMediaSrc		media src
EMediaSysHypBitrate	media system-bitrate
EMediaSysHypCap		media system-captions
EMediaSysHypLang	media system-language
EMediaSysHypOverCap	media system-overdub-or-caption caption overdub
EMediaSysHypReq		media system-required
EMediaSysHypScrnDepth	media system-screen-depth
EMediaSysHypScrnSize	media system-screen-size
EMediaSysAudioDesc	media systemAudioDesc off on
EMediaSysBitrate	media systemBitrate
EMediaSysCPU		media systemCPU
EMediaSysCaptions  	media systemCaptions off on
EMediaSysComp		media systemComponent
EMediaSysLang		media systemLanguage
EMediaSysOS		media systemOperatingSystem
EMediaSysOverCap	media systemOverdubOrSubtitle overdub subtitle
EMediaSysReq		media systemRequired
EMediaSysScrnDepth	media systemScreenDepth
EMediaSysScrnSize	media systemScreenSize
EMediaTitle		media title
EMediaTransIn		media transIn
EMediaTransOut		media transOut
EMediaType		media type
EMediaXMLLang		media xml:lang
EMetaClass		meta class
EMetaContent		meta content
EMetaId			meta id
EMetaName		meta name
EMetaSkipContent	meta skip-content false true
EMetaTitle		meta title
EMetaXMLLang		meta xml:lang
EMetadataClass		metadata class
EMetadataId		metadata id
EMetadataSkipContent	metadata skip-content false true
EMetadataTitle		metadata title
EMetadataXMLLang	metadata xml:lang
EPrefetchBandwith	prefetch bandwidth
EPrefetchClass		prefetch class
EPrefetchId		prefetch id
EPrefetchMediaSize	prefetch mediaSize
EPrefetchMediaTime	prefetch mediaTime
EPrefetchSkipContent	prefetch skip-content false true
EPrefetchSrc		prefetch src
EPrefetchSysAudioDesc	prefetch systemAudioDesc off on
EPrefetchSysBitrate	prefetch systemBitrate
EPrefetchSysCPU		prefetch systemCPU
EPrefetchSysCaptions	prefetch systemCaptions off on
EPrefetchSysComp	prefetch systemComponent
EPrefetchSysLang	prefetch systemLanguage
EPrefetchSysOS		prefetch systemOperatingSystem
EPrefetchSysOvrdubSub 	prefetch systemOverdubOrSubtitle
EPrefetchSysRequired  	prefetch systemRequired
EPrefetchSysScrnDepth 	prefetch systemScreenDepth
EPrefetchSysScrnSize  	prefetch systemScreenSize
EPrefetchTitle		prefetch title
EPrefetchXMLLang	prefetch xml:lang
ERegionBGHypCol		region background-color
ERegionBGCol		region backgroundColor
ERegionBottom		region bottom
ERegionClass		region class
ERegionClose		region close never whenNotActive
ERegionFit		region fit fill hidden meet scroll slice
ERegionHeight		region height
ERegionId		region id
ERegionLeft		region left
ERegionOpen		region open always whenActive
ERegionRegionName	region regionName
ERegionRight		region right
ERegionShowBG		region showBackground always whenActive
ERegionSkipContent	region skip-content false true
ERegionTitle		region title
ERegionTop		region top
ERegionWidth		region width
ERegionXMLLang		region xml:lang
ERegionZIndex		region z-index
ERootLayoutBGHypCol	root-layout background-color
ERootLayoutBGCol	root-layout backgroundColor
ERootLayoutClass	root-layout class
ERootLayoutClose	root-layout close never whenNotActive
ERootLayoutHeight	root-layout height
ERootLayoutId		root-layout id
ERootLayoutOpen		root-layout open always whenActive
ERootLayoutSkipContent  root-layout skip-content false true
ERootLayoutTitle	root-layout title
ERootLayoutWidth	root-layout width
ERootLayoutXMLLang	root-layout xml:lang
ESMILClass		smil class
ESMILId			smil id
ESMILSysAudioDesc	smil systemAudioDesc off on
ESMILSysBitrate		smil systemBitrate
ESMILSysCPU		smil systemCPU
ESMILSysCaptions	smil systemCaptions off on
ESMILSysComp		smil systemComponent
ESMILSysLang		smil systemLanguage
ESMILSysOS		smil systemOperatingSystem
ESMILSysOverCap		smil systemOverdubOrSubtitle overdub subtitle
ESMILSysReq		smil systemRequired
ESMILSysScrnDepth	smil systemScreenDepth
ESMILSysScrnSize	smil systemScreenSize
ESMILTitle		smil title
ESMILXMLLang		smil xml:lang
ESMILXMLNS		smil xmlns
ESwitchClass		switch class
ESwitchId		switch id
ESwitchSysAudioDesc	switch systemAudioDesc off on
ESwitchSysBitrate	switch systemBitrate
ESwitchSysCPU		switch systemCPU
ESwitchSysCaptions	switch systemCaptions off on
ESwitchSysComp		switch systemComponent
ESwitchSysLang		switch systemLanguage
ESwitchSysOS		switch systemOperatingSystem
ESwitchSysOverCap	switch systemOverdubOrSubtitle overdub subtitle
ESwitchSysReq		switch systemRequired
ESwitchSysScrnDepth	switch systemScreenDepth
ESwitchSysScrnSize	switch systemScreenSize
ESwitchTitle		switch title
ESwitchXMLLang		switch xml:lang
ETimingAbstract		timing abstract
ETimingAuthor		timing author
ETimingBegin		timing begin
ETimingClass		timing class
ETimingCopyright	timing copyright
ETimingCustomTest	timing customTest
ETimingDur		timing dur
ETimingEnd		timing end
ETimingEndSync		timing endsync
ETimingFill		timing fill freeze hold remove transition
ETimingId		timing id
ETimingMax		timing max
ETimingMin		timing min
ETimingRepeat		timing repeat
ETimingRepeatCount	timing repeatCount
ETimingRepeatDur	timing repeatDur
ETimingSysHypBitRate	timing system-bitrate
ETimingSysHypCaptions	timing system-captions on off
ETimingSysHypLang	timing system-language
ETimingSysHypOverCap	timing system-overdub-or-caption caption overdub
ETimingSysHypReq	timing system-required
ETimingSysHypScrnDepth	timing system-screen-depth
ETimingSysHypScrnSize   timing system-screen-size
ETimingSysAudioDesc	timing systemAudioDesc off on
ETimingSysBitrate	timing systemBitrate
ETimingSysCPU		timing systemCPU
ETimingSysCaptions	timing systemCaptions off on
ETimingSysComp		timing systemComponent
ETimingSysLang		timing systemLanguage
ETimingSysOS		timing systemOperatingSystem
ETimingSysOverdubSub	timing systemOverdubOrSubtitle
ETimingSysReq		timing systemRequired
ETimingSysScrnDepth	timing systemScreenDepth
ETimingSysScrnSize	timing systemScreenSize
ETimingTitle		timing title
ETimingXMLLAng		timing xml:lang
ETransitionClass	transition class
ETransitionDirecton	transition direction forward reverse
ETransitionDur		transition dur
ETransitionEndProg	transition endProgress
ETransitionFadeCol	transition fadeColor
ETransitionId		transition id
ETransitionSkipContent  transition skip-content false true
ETransitionStartProg	transition startProgress
ETransitionSubtype	transition subtype
ETransitionSysAudioDesc	transition systemAudioDesc off on
ETransitionSysBitrate	transition systemBitrate
ETransitionSysCPU	transition systemCPU
ETransitionSysCaptions	transition systemCaptions off on
ETransitionSysComp	transition systemComponent
ETransitionSysLang	transition systemLanguage
ETransitionSysOS	transition systemOperatingSystem
ETransitionSysOvrdubSub transition systemOverdubOrSubtitle
ETransitionSysRequired  transition systemRequired
ETransitionSysScrnDepth transition systemScreenDepth
ETransitionSysScrnSize  transition systemScreenSize
ETransitionTitle	transition title
ETransitionType		transition type 
ETransitionXMLLang	transition xml:lang
