// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __NOTESAPPLICATIONTRACES_H__
#define __NOTESAPPLICATIONTRACES_H__

#define KOstTraceComponentID 0x20029f80

#define NOTESAPPLICATION_NOTESAPPLICATION_ENTRY 0x8a0002
#define NOTESAPPLICATION_NOTESAPPLICATION_EXIT 0x8a0003
#define DUP1_NOTESAPPLICATION_NOTESAPPLICATION_ENTRY 0x8a0004
#define DUP1_NOTESAPPLICATION_NOTESAPPLICATION_EXIT 0x8a0005
#define NOTESAPPLICATION_CREATECONTROLLER_ENTRY 0x8a0006
#define NOTESAPPLICATION_CREATECONTROLLER_EXIT 0x8a0007
#define NOTESAPPLICATION_EXECUTION_ENTRY 0x8a0008
#define NOTESAPPLICATION_EXECUTION_EXIT 0x8a0009
#define NOTESAPPLICATION_HANDLEAPPREADY_ENTRY 0x8a000a
#define NOTESAPPLICATION_HANDLEAPPREADY_EXIT 0x8a000b


#endif

// End of file

