//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
PRINT Run all smcmsuite_gsm Tests 
//
LOAD_SUITE smcmsuite_gsm -SharedData
//

RUN_TEST_STEP 100 smcmsuite_gsm SMCMStepInitialise

RUN_TEST_STEP 100 smcmsuite_gsm SMCMStepSettings

RUN_TEST_STEP 100 smcmsuite_gsm SMCMStepQueryCapabilities

RUN_TEST_STEP 100 smcmsuite_gsm SMCMStepFind

RUN_TEST_STEP 100 smcmsuite_gsm SMCMStepFindAlias

RUN_TEST_STEP 100 smcmsuite_gsm SMCMStepReply

RUN_TEST_STEP 100 smcmsuite_gsm SMCMStepReplyEmail

RUN_TEST_STEP 100 smcmsuite_gsm SMCMStepForward

RUN_TEST_STEP 100 smcmsuite_gsm SMCMStepForwardEmail

