######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 3 15:16:30 2009
######################################################################

TEMPLATE = subdirs
SUBDIRS += alarmalertplugin \
		   alarmalertinterface
		   
CONFIG += ordered
