//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

[All]
Defaults= defaults.script
Bearer= NBS

[Message]
Message=
1
From: 01514876655
Subject: Los huevos del perro (something about your dog)
BioUid= 268457264
Bearer= NBS

[NBS:ComBizCardBigger]
Bearer= NBS
BioUid= 268457265
Message= 
Business Card
Da Card
Biz Cards Lmtd
Biz Whiz
tel 411
tel (home) 411
fax 411
me@here.com
1122 Boogie Woogie Avenue
Big Town
WC1 000
United Kingdom
Gubbins
More Gubbins
Huge heaps of Gubbins
Mountain of Gubbins, higher than is possibly feasible.

endscript