//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

RUN_UTILS  CopyFile c:\msgtest\sms\ReplyToConfig.txt c:\config.txt
RUN_UTILS  MakeReadWrite c:\config.txt

PRINT Run all t_SmsReplyToServer Tests 
LOAD_SUITE t_SmsReplyToServer -SharedData
RUN_TEST_STEP  1000 t_SmsReplyToServer SmsReplyToStep1
