//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all t_smcs2 Tests 
LOAD_SUITE t_smcs2_server -SharedData
RUN_TEST_STEP 1000 t_smcs2_server TestSmsEntry
RUN_TEST_STEP 1000 t_smcs2_server TestSmsSettings
RUN_TEST_STEP 1000 t_smcs2_server TestSmsNumber 
RUN_TEST_STEP 1000 t_smcs2_server TestEmailFields 
RUN_TEST_STEP 1000 t_smcs2_server TestSmsHeader
RUN_TEST_STEP 1000 t_smcs2_server TestSmsUtilities
RUN_TEST_STEP 1000 t_smcs2_server TestSmsEmsExtensions