//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

[All]
Defaults= defaults.script
Bearer= WAP

[VCal]
Message= BEGIN:VCALENDAR
VERSION:1.0
BEGIN:VEVENT
CATEGORIES:MEETING
DTSTART:20000610T090000
DALARM:20000610T085900;;;
AALARM:20000610T085900;;;
SUMMARY:B
DESCRIPTION:Meet Santa
END:VEVENT
END:VCALENDAR
BioUid= 268457267

[VCard]
Message=
begin:vcard
n:;Julia
adr:;;;;;;
version:2.1
email;internet:julia.blumin@symbian.com
fn:Julia Blumin
end:vcard
BioUid= 268457268
Bearer= WAP
Encoding= 8

[RT]
File= tone1.rtp
BioUid= 268457269
Encoding= 8

[Logo]
File= logo1.olp
BioUid= 268457270
Encoding= 8

endscript

[RT]
File= tone2.rtp
BioUid= 268457269
Encoding= 8

[RT]
File= c:\test\sms\tone3.rtp
BioUid= 268457269
Encoding= 8
