// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CLOCKDOCLOADERTRACES_H__
#define __CLOCKDOCLOADERTRACES_H__

#define KOstTraceComponentID 0x2002bce5

#define CLOCKDOCLOADER_CREATEOBJECT_ENTRY 0x8a0001
#define CLOCKDOCLOADER_CREATEOBJECT_EXIT 0x8a0002
#define DUP1_CLOCKDOCLOADER_CREATEOBJECT_EXIT 0x8a0003
#define DUP2_CLOCKDOCLOADER_CREATEOBJECT_EXIT 0x8a0004
#define DUP3_CLOCKDOCLOADER_CREATEOBJECT_EXIT 0x8a0005


#endif

// End of file

