// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CLOCKVIEWMANAGERTRACES_H__
#define __CLOCKVIEWMANAGERTRACES_H__

#define KOstTraceComponentID 0x2002bce5

#define CLOCKVIEWMANAGER_CLOCKVIEWMANAGER_ENTRY 0x8a0006
#define CLOCKVIEWMANAGER_CLOCKVIEWMANAGER_EXIT 0x8a0007
#define DUP1_CLOCKVIEWMANAGER_CLOCKVIEWMANAGER_ENTRY 0x8a0008
#define DUP1_CLOCKVIEWMANAGER_CLOCKVIEWMANAGER_EXIT 0x8a0009
#define CLOCKVIEWMANAGER_SHOWVIEW_ENTRY 0x8a000a
#define CLOCKVIEWMANAGER_SHOWVIEW_EXIT 0x8a000b
#define CLOCKVIEWMANAGER_LOADMAINVIEW_ENTRY 0x8a000c
#define CLOCKVIEWMANAGER_LOADMAINVIEW_EXIT 0x8a000d
#define CLOCKVIEWMANAGER_LOADWORLDCLOCKVIEW_ENTRY 0x8a000e
#define CLOCKVIEWMANAGER_LOADWORLDCLOCKVIEW_EXIT 0x8a000f
#define CLOCKVIEWMANAGER_LOADOTHERVIEWS_ENTRY 0x8a0010
#define CLOCKVIEWMANAGER_LOADOTHERVIEWS_EXIT 0x8a0011


#endif

// End of file

