// Copyright (c) 1997-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
#ifndef __VERSITTLSCONTAINER_H__
#define __VERSITTLSCONTAINER_H__

#include <e32base.h>

NONSHARABLE_CLASS( CVersitTLSContainer ): public CBase	
/**
Wrapper class for static variables to be stored in TLS
@internalComponent
@released
*/
	{
public:
	static CVersitTLSContainer *NewLC(const TInt aSize);
	~CVersitTLSContainer();
public:
	HBufC * iShiftJisEscape;//Store shift-jis escape charcter, as generated by relevant charconv plugin	
	};
#endif //__VERSITTLSCONTAINER_H__