//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all t_popsecuresocket Tests 
LOAD_SUITE t_popsecuresockets

PRINT Run all t_popsecuresocket Tests 
LOAD_SUITE t_popsecuresockets
//RUN_TEST_STEP 1000 t_popsecuresockets TEFUnit.CTestPOPSecureSocketTest.*
RUN_TEST_STEP 1000 t_popsecuresockets TEFUnit.CTestPopSaslAuthHelper.*