/*
* Copyright (c) 2010 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: Definition of AgendaEventViewerPrivate class
*
*/
// Created by TraceCompiler 2.2.4
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __AGENDAEVENTVIEWER_PTRACES_H__
#define __AGENDAEVENTVIEWER_PTRACES_H__

#define KOstTraceComponentID 0x2002c367

#define AGENDAEVENTVIEWERPRIVATE_AGENDAEVENTVIEWERPRIVATE_ENTRY 0x8a005d
#define AGENDAEVENTVIEWERPRIVATE_AGENDAEVENTVIEWERPRIVATE_EXIT 0x8a005e
#define DUP1_AGENDAEVENTVIEWERPRIVATE_AGENDAEVENTVIEWERPRIVATE_ENTRY 0x8a005f
#define DUP1_AGENDAEVENTVIEWERPRIVATE_AGENDAEVENTVIEWERPRIVATE_EXIT 0x8a0060
#define AGENDAEVENTVIEWERPRIVATE_VIEW_ENTRY 0x8a0061
#define AGENDAEVENTVIEWERPRIVATE_VIEW_EXIT 0x8a0062
#define DUP1_AGENDAEVENTVIEWERPRIVATE_VIEW_EXIT 0x8a0063
#define DUP1_AGENDAEVENTVIEWERPRIVATE_VIEW_ENTRY 0x8a0064
#define DUP2_AGENDAEVENTVIEWERPRIVATE_VIEW_EXIT 0x8a0065
#define DUP2_AGENDAEVENTVIEWERPRIVATE_VIEW_ENTRY 0x8a0066
#define DUP3_AGENDAEVENTVIEWERPRIVATE_VIEW_EXIT 0x8a0067
#define DUP4_AGENDAEVENTVIEWERPRIVATE_VIEW_EXIT 0x8a0068
#define AGENDAEVENTVIEWERPRIVATE_VIEWINGCOMPLETED_ENTRY 0x8a0069
#define AGENDAEVENTVIEWERPRIVATE_VIEWINGCOMPLETED_EXIT 0x8a006a
#define AGENDAEVENTVIEWERPRIVATE_EDITINGSTARTED_ENTRY 0x8a006b
#define AGENDAEVENTVIEWERPRIVATE_EDITINGSTARTED_EXIT 0x8a006c
#define AGENDAEVENTVIEWERPRIVATE_EDITINGCOMPLETED_ENTRY 0x8a006d
#define AGENDAEVENTVIEWERPRIVATE_EDITINGCOMPLETED_EXIT 0x8a006e
#define AGENDAEVENTVIEWERPRIVATE_DELETINGSTARTED_ENTRY 0x8a006f
#define AGENDAEVENTVIEWERPRIVATE_DELETINGSTARTED_EXIT 0x8a0070
#define AGENDAEVENTVIEWERPRIVATE_DELETINGCOMPLETED_ENTRY 0x8a0071
#define AGENDAEVENTVIEWERPRIVATE_DELETINGCOMPLETED_EXIT 0x8a0072
#define AGENDAEVENTVIEWERPRIVATE_VIEWCREATIONCOMPLETED_ENTRY 0x8a0073
#define AGENDAEVENTVIEWERPRIVATE_VIEWCREATIONCOMPLETED_EXIT 0x8a0074


#endif

// End of file

