// Copyright (c) 2002-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

RUN_UTILS  DeleteFile C:\Config.txt
RUN_UTILS  CopyFile Z:\TestData\Configs\TE_PhBkSync_Config.txt C:\Config.txt
RUN_UTILS  MakeReadWrite C:\Config.txt

ced Z:\TestData\Configs\TE_PhBkSync.cfg ced.log
