// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __ALARMALERTWRAPPERTRACES_H__
#define __ALARMALERTWRAPPERTRACES_H__

#define KOstTraceComponentID 0xe2eb3dbf

#define ALARMALERT_ALARMALERT_ENTRY 0x8a0012
#define ALARMALERT_ALARMALERT_EXIT 0x8a0013
#define DUP1_ALARMALERT_ALARMALERT_ENTRY 0x8a0014
#define DUP1_ALARMALERT_ALARMALERT_EXIT 0x8a0015
#define ALARMALERT_SHOWALARMALERT_ENTRY 0x8a0016
#define ALARMALERT_DISMISSALARMALERT_ENTRY 0x8a0017
#define ALARMALERT_DISMISSALARMALERT_EXIT 0x8a0018
#define ALARMALERT_UPDATEALARMALERT_ENTRY 0x8a0019


#endif

// End of file

