// Created by TraceCompiler 2.1.2
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __GLXCOMMANDHANDLERDELETETRACES_H__
#define __GLXCOMMANDHANDLERDELETETRACES_H__

#define KOstTraceComponentID 0x20000a0d

#define GLXCOMMANDHANDLERDELETE_GLXCOMMANDHANDLERDELETE_ENTRY 0x8a0001
#define GLXCOMMANDHANDLERDELETE_GLXCOMMANDHANDLERDELETE_EXIT 0x8a0002
#define DUP1_GLXCOMMANDHANDLERDELETE_GLXCOMMANDHANDLERDELETE_ENTRY 0x8a0003
#define DUP1_GLXCOMMANDHANDLERDELETE_GLXCOMMANDHANDLERDELETE_EXIT 0x8a0004
#define GLXCOMMANDHANDLERDELETE_CREATECOMMANDL_ENTRY 0x8a0005
#define GLXCOMMANDHANDLERDELETE_CREATECOMMANDL_EXIT 0x8a0006


#endif

// End of file

