// Created by TraceCompiler 2.1.2
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __GLXCOMMANDHANDLERTRACES_H__
#define __GLXCOMMANDHANDLERTRACES_H__

#define KOstTraceComponentID 0x20000a11

#define GLXCOMMANDHANDLER_GLXCOMMANDHANDLER_ENTRY 0x8a0001
#define GLXCOMMANDHANDLER_GLXCOMMANDHANDLER_EXIT 0x8a0002
#define DUP1_GLXCOMMANDHANDLER_GLXCOMMANDHANDLER_ENTRY 0x8a0003
#define DUP1_GLXCOMMANDHANDLER_GLXCOMMANDHANDLER_EXIT 0x8a0004


#endif

// End of file

