// Created by TraceCompiler 2.1.2
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __GLXFULLSCREENVIEWTRACES_H__
#define __GLXFULLSCREENVIEWTRACES_H__

#define KOstTraceComponentID 0x200009ef

#define GLXFULLSCREENVIEW_GLXFULLSCREENVIEW_ENTRY 0x8a000d
#define GLXFULLSCREENVIEW_GLXFULLSCREENVIEW_EXIT 0x8a000e
#define GLXFULLSCREENVIEW_INITIALIZEVIEW_ENTRY 0x8a000f
#define GLXFULLSCREENVIEW_INITIALIZEVIEW_EXIT 0x8a0010
#define GLXFULLSCREENVIEW_LOADWIDGETS_ENTRY 0x8a0011
#define GLXFULLSCREENVIEW_LOADWIDGETS_EXIT 0x8a0012
#define GLXFULLSCREENVIEW_LOADFULLSCREENTOOLBAR_ENTRY 0x8a0013
#define GLXFULLSCREENVIEW_LOADFULLSCREENTOOLBAR_EXIT 0x8a0014
#define GLXFULLSCREENVIEW_ACTIVATE_ENTRY 0x8a0015
#define GLXFULLSCREENVIEW_ACTIVATE_EXIT 0x8a0016
#define GLXFULLSCREENVIEW_LOADVIEWSECTION_ENTRY 0x8a0017
#define GLXFULLSCREENVIEW_LOADVIEWSECTION_EXIT 0x8a0018
#define GLXFULLSCREENVIEW_RESETVIEW_ENTRY 0x8a0019
#define GLXFULLSCREENVIEW_RESETVIEW_EXIT 0x8a001a
#define GLXFULLSCREENVIEW_DEACTIVATE_ENTRY 0x8a001b
#define GLXFULLSCREENVIEW_DEACTIVATE_EXIT 0x8a001c
#define GLXFULLSCREENVIEW_CLEANUP_ENTRY 0x8a001d
#define GLXFULLSCREENVIEW_CLEANUP_EXIT 0x8a001e
#define GLXFULLSCREENVIEW_SETMODEL_ENTRY 0x8a001f
#define GLXFULLSCREENVIEW_SETMODEL_EXIT 0x8a0020
#define GLXFULLSCREENVIEW_SETMODELCONTEXT_ENTRY 0x8a0021
#define GLXFULLSCREENVIEW_SETMODELCONTEXT_EXIT 0x8a0022
#define GLXFULLSCREENVIEW_ORIENTATIONCHANGED_ENTRY 0x8a0023
#define GLXFULLSCREENVIEW_ORIENTATIONCHANGED_EXIT 0x8a0024
#define GLXFULLSCREENVIEW_ACTIVATEUI_ENTRY 0x8a0025
#define GLXFULLSCREENVIEW_ACTIVATEUI_EXIT 0x8a0026
#define GLXFULLSCREENVIEW_HIDEUI_ENTRY 0x8a0027
#define GLXFULLSCREENVIEW_HIDEUI_EXIT 0x8a0028
#define DUP1_GLXFULLSCREENVIEW_HIDEUI_EXIT 0x8a0029
#define GLXFULLSCREENVIEW_CHANGESELECTEDINDEX_ENTRY 0x8a002a
#define GLXFULLSCREENVIEW_CHANGESELECTEDINDEX_EXIT 0x8a002b
#define DUP1_GLXFULLSCREENVIEW_CHANGESELECTEDINDEX_EXIT 0x8a002c
#define GLXFULLSCREENVIEW_INDEXCHANGED_ENTRY 0x8a002d
#define GLXFULLSCREENVIEW_INDEXCHANGED_EXIT 0x8a002e
#define DUP1_GLXFULLSCREENVIEW_INDEXCHANGED_EXIT 0x8a002f
#define GLXFULLSCREENVIEW_SCROLLINGSTARTED_ENTRY 0x8a0030
#define GLXFULLSCREENVIEW_SCROLLINGSTARTED_EXIT 0x8a0031
#define GLXFULLSCREENVIEW_SCROLLINGENDED_ENTRY 0x8a0032
#define GLXFULLSCREENVIEW_SCROLLINGENDED_EXIT 0x8a0033
#define GLXFULLSCREENVIEW_PRESSED_ENTRY 0x8a0034
#define GLXFULLSCREENVIEW_PRESSED_EXIT 0x8a0035
#define GLXFULLSCREENVIEW_RELEASED_ENTRY 0x8a0036
#define GLXFULLSCREENVIEW_RELEASED_EXIT 0x8a0037
#define GLXFULLSCREENVIEW_SETVISVALWINDOWINDEX_ENTRY 0x8a0038
#define GLXFULLSCREENVIEW_SETVISVALWINDOWINDEX_EXIT 0x8a0039
#define GLXFULLSCREENVIEW_COVERFLOWEVENTHANDLE_ENTRY 0x8a003a
#define GLXFULLSCREENVIEW_COVERFLOWEVENTHANDLE_EXIT 0x8a003b
#define GLXFULLSCREENVIEW_EFFECTFINISHED_ENTRY 0x8a003c
#define GLXFULLSCREENVIEW_EFFECTFINISHED_EXIT 0x8a003d
#define GLXFULLSCREENVIEW_IMAGESELECTIONEFFECTFINISHED_ENTRY 0x8a003e
#define GLXFULLSCREENVIEW_IMAGESELECTIONEFFECTFINISHED_EXIT 0x8a003f
#define GLXFULLSCREENVIEW_SETLAYOUT_ENTRY 0x8a0040
#define GLXFULLSCREENVIEW_SETLAYOUT_EXIT 0x8a0041
#define GLXFULLSCREENVIEW_ADDCONNECTION_ENTRY 0x8a0042
#define GLXFULLSCREENVIEW_ADDCONNECTION_EXIT 0x8a0043
#define GLXFULLSCREENVIEW_REMOVECONNECTION_ENTRY 0x8a0044
#define GLXFULLSCREENVIEW_REMOVECONNECTION_EXIT 0x8a0045
#define GLXFULLSCREENVIEW_SETIMAGESTRIPMODEL_ENTRY 0x8a0046
#define GLXFULLSCREENVIEW_SETIMAGESTRIPMODEL_EXIT 0x8a0047
#define DUP1_GLXFULLSCREENVIEW_GLXFULLSCREENVIEW_ENTRY 0x8a0048
#define DUP1_GLXFULLSCREENVIEW_GLXFULLSCREENVIEW_EXIT 0x8a0049
#define GLXFULLSCREENVIEW_HANDLEUSERACTION_ENTRY 0x8a004a
#define GLXFULLSCREENVIEW_HANDLEUSERACTION_EXIT 0x8a004b
#define GLXFULLSCREENVIEW_SETIMAGETOHDMIL_ENTRY 0x8a004c
#define GLXFULLSCREENVIEW_SETIMAGETOHDMIL_EXIT 0x8a004d
#define GLXFULLSCREENVIEW_IMAGESELECTIONANIMATION_ENTRY 0x8a004e
#define GLXFULLSCREENVIEW_IMAGESELECTIONANIMATION_EXIT 0x8a004f
#define GLXFULLSCREENVIEW_HANDLETOOLBARACTION_ENTRY 0x8a0050
#define GLXFULLSCREENVIEW_HANDLETOOLBARACTION_EXIT 0x8a0051
#define GLXFULLSCREENVIEW_ACTIVATE 0x860018
#define GLXFULLSCREENVIEW_CLEANUP 0x860019
#define DUP1_GLXFULLSCREENVIEW_CLEANUP 0x86001a
#define DUP2_GLXFULLSCREENVIEW_CLEANUP 0x86001b
#define GLXFULLSCREENVIEW_SETMODEL 0x86001c
#define GLXFULLSCREENVIEW_SETIMAGETOHDMIL 0x86001d
#define DUP1_GLXFULLSCREENVIEW_SETIMAGETOHDMIL 0x86001e


inline TBool OstTraceGen2( TUint32 aTraceID, TUint aParam1, TUint aParam2 )
    {
    TBool retval = BTraceFiltered8( EXTRACT_GROUP_ID(aTraceID), EOstTraceActivationQuery, KOstTraceComponentID, aTraceID );
    if ( retval )
        {
        TUint8 data[ 8 ];
        TUint8* ptr = data;
        *( ( TUint* )ptr ) = aParam1;
        ptr += sizeof ( TUint );
        *( ( TUint* )ptr ) = aParam2;
        ptr += sizeof ( TUint );
        ptr -= 8;
        retval = OstSendNBytes( EXTRACT_GROUP_ID(aTraceID), EOstTrace, KOstTraceComponentID, aTraceID, ptr, 8 );
        }
    return retval;
    }

inline TBool OstTraceGen2( TUint32 aTraceID, TUint32 aParam1, TUint32 aParam2 )
    {
    TBool retval = BTraceFiltered8( EXTRACT_GROUP_ID(aTraceID), EOstTraceActivationQuery, KOstTraceComponentID, aTraceID );
    if ( retval )
        {
        TUint8 data[ 8 ];
        TUint8* ptr = data;
        *( ( TUint* )ptr ) = aParam1;
        ptr += sizeof ( TUint );
        *( ( TUint* )ptr ) = aParam2;
        ptr += sizeof ( TUint );
        ptr -= 8;
        retval = OstSendNBytes( EXTRACT_GROUP_ID(aTraceID), EOstTrace, KOstTraceComponentID, aTraceID, ptr, 8 );
        }
    return retval;
    }


#endif

// End of file

