/*
* Copyright (c) 2005 - 2010 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  Macro definition file for logging.
*
*/

// Autogenerated from .\phonestatestrings.st by the stringtable tool - Do not edit
#include <e32std.h>
#include <stringpool.h>
#include <stringtablesupport.h>
#include "phonestatestrings.h"
#ifdef _DEBUG
#undef _DEBUG
#endif

_STLIT8(K1, "EPhoneStateNull");
_STLIT8(K2, "EPhoneStateStartup");
_STLIT8(K3, "EPhoneStateIdle");
_STLIT8(K4, "EPhoneStateCallSetup");
_STLIT8(K5, "EPhoneStateSingle");
_STLIT8(K6, "EPhoneStateIncoming");
_STLIT8(K7, "EPhoneStateEmergency");

// Intermediate
const void * const KStringPointers[] =
	{
	(const void*)&K1,
	(const void*)&K2,
	(const void*)&K3,
	(const void*)&K4,
	(const void*)&K5,
	(const void*)&K6,
	(const void*)&K7
	};

const TStringTable PhoneStateStrings::Table = {7, KStringPointers, EFalse};

