/*
* Copyright (c) 2005 - 2010 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  Macro definition file for logging.
*
*/

// Autogenerated from .\phonestatestringsgsm.st by the stringtable tool - Do not edit
#include <e32std.h>
#include <stringpool.h>
#include <stringtablesupport.h>
#include "phonestatestringsgsm.h"
#ifdef _DEBUG
#undef _DEBUG
#endif

_STLIT8(K1, "EPhoneStateAlerting");
_STLIT8(K2, "EPhoneStateAlertingInSingle");
_STLIT8(K3, "EPhoneStateWaitingInSingle");
_STLIT8(K4, "EPhoneStateTwoSingles");
_STLIT8(K5, "EPhoneStateCallSetupInSingle");
_STLIT8(K6, "EPhoneStateConference");
_STLIT8(K7, "EPhoneStateConferenceAndCallSetup");
_STLIT8(K8, "EPhoneStateConferenceAndSingle");
_STLIT8(K9, "EPhoneStateConferenceAndWaiting");
_STLIT8(K10, "EPhoneStateSingleAndCallSetupAndWaiting");
_STLIT8(K11, "EPhoneStateCallSetupAndWaiting");
_STLIT8(K12, "EPhoneStateTwoSinglesAndWaiting");
_STLIT8(K13, "EPhoneStateConferenceAndSingleAndWaiting");
_STLIT8(K14, "EPhoneStateConferenceAndWaitingAndCallSetup");
_STLIT8(K15, "EPhoneStateLastGSMState");

// Intermediate
const void * const KStringPointers[] =
	{
	(const void*)&K1,
	(const void*)&K2,
	(const void*)&K3,
	(const void*)&K4,
	(const void*)&K5,
	(const void*)&K6,
	(const void*)&K7,
	(const void*)&K8,
	(const void*)&K9,
	(const void*)&K10,
	(const void*)&K11,
	(const void*)&K12,
	(const void*)&K13,
	(const void*)&K14,
	(const void*)&K15
	};

const TStringTable PhoneStateStringsGSM::Table = {15, KStringPointers, EFalse};

