// Copyright (c) 2004-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

RUN_UTILS  DeleteFile c:\config.txt
RUN_UTILS  CopyFile z:\TestData\Configs\TE_CntSync_config.txt c:\config.txt
RUN_UTILS  MakeReadWrite c:\config.txt
//
ced -i z:\TestData\configs\te_cntsync.cfg ced.log
