From: "Emlyn" <test@psion9.demon.co.uk>
To: <emlyn.howell@symbian.com>
Subject: a picture in a mail
Date: Thu, 27 Jan 2000 11:05:21 -0000
MIME-Version: 1.0
Content-Type: multipart/related;
	type="multipart/alternative";
	boundary="----=_NextPart_000_0022_01BF68B6.67877390"
X-Priority: 3
X-MSMail-Priority: Normal
X-Mailer: Microsoft Outlook Express 5.00.2919.6600
X-MimeOLE: Produced By Microsoft MimeOLE V5.00.2919.6600

This is a multi-part message in MIME format.

------=_NextPart_000_0022_01BF68B6.67877390
Content-Type: multipart/alternative;
	boundary="----=_NextPart_001_0023_01BF68B6.67877390"


------=_NextPart_001_0023_01BF68B6.67877390
Content-Type: text/plain;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

a picture...



------=_NextPart_001_0023_01BF68B6.67877390
Content-Type: text/html;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<META content=3D"text/html; charset=3Diso-8859-1" =
http-equiv=3DContent-Type>
<META content=3D"MSHTML 5.00.2919.6307" name=3DGENERATOR>
<STYLE></STYLE>
</HEAD>
<BODY bgColor=3D#c0c0c0>
<DIV><FONT face=3DArial size=3D2>a picture...</FONT></DIV>
<DIV>&nbsp;</DIV>
<DIV><IMG align=3Dbaseline alt=3D"" border=3D0 hspace=3D0=20
src=3D"cid:002101bf68b6$6782dfb0$060b970a@intra"></DIV></BODY></HTML>

------=_NextPart_001_0023_01BF68B6.67877390--

------=_NextPart_000_0022_01BF68B6.67877390
Content-Type: image/gif;
	name="logo1.gif"
Content-Transfer-Encoding: base64
Content-ID: <002101bf68b6$6782dfb0$060b970a@intra>

R0lGODlhkQAuAMQAAP////+ZAMz//8zM/8zMzMyZM8yZAJn//5nMzJmZzJmZM2b//2bMzGaZzGaZ
ZjPMzDOZmTOZZjNmmQCZmQBmmQBmZgAzMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAFk
AAAALAAAAACRAC4AAAX/ICCOZGmeaKqubOu+cCzPdG3feK7vfO//wKBwSCwaj7aKLAJBOo8Vy2Wq
dEUCWMVzK5x6LS8DFuvgmnveKdg1zp7fufRl3WoHyvA8TU5nOcYGeoIyfDARCniDii2Fi0kVkI4j
jZFPVThRcmokFp1UJ1GdnVWQUkpSX5eZXyZ8qKwoFLIpq2l9I6tVr3OXLLuacyKNJb/CtsAXSsgX
JctyvSOyFCe/mr2uyNAo1ZprmieN3M7AfeNp2tIlFeZTnOztK+vmpM/q9QDy78sk+swk0rNwvbsk
Dpg2YsNW8bOFMI3AbuI8yVnIp5aXXgCnuftiwWIwEfn4dFtRbMU3iptA/yZceW7SxBHV/gFs9dEl
LHzWbKZM8esgiZD+VLYU6qWZQ5TJdNY0dlRERhMHd9EB2ksqyW6VwA0FUJIoPKVGLyq9ldPpTBWQ
LE69J8IqWmcdad4chrMp0693k+a91TPaWXUFa1LduDMFO3tN2dYtijTsp70NxZpNF3nZ2q1cGcY7
jFQJUMSMwXYeW1kvgKdILT+U3Fazr3HlGLpdjRfAS6WX6Gbeiro1xNmDYbp2EWokbWa3jzsOmjf3
8N2se9tmC1zx7BhAmU+/mNyr9u5sdZ+cHBCy8JvBfRdG4bOr+rI/wdvd/pj+0uwyKZt/f5k19KWg
8CLXetmFFt988rHW1697pp32l33MVYfZdVqlAgl8St10oIH2LacKRMCUIF1Z6aX33y2gmUONQQEi
6KJ/gfnnoH7/qXZcVc+VtoxPIbbIYYL1MWiciOVlOKR3OGoISmAobrieco2NlqJi+UHljDYmUkiL
KKL45CEtaUETpphhbsmllzOyx+UoYKalTplCfCbJnDloSeedL7iH554sZNckn4CmVlughJ6HWaGI
hvQnooSyyeijkEYq6aSULhICADs=

------=_NextPart_000_0022_01BF68B6.67877390--
