// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __NOTESMODELHANDLERTRACES_H__
#define __NOTESMODELHANDLERTRACES_H__

#define KOstTraceComponentID 0x2002bcdc

#define NOTESMODELHANDLER_NOTESMODELHANDLER_ENTRY 0x8a0001
#define NOTESMODELHANDLER_NOTESMODELHANDLER_EXIT 0x8a0002
#define DUP1_NOTESMODELHANDLER_NOTESMODELHANDLER_ENTRY 0x8a0003
#define DUP1_NOTESMODELHANDLER_NOTESMODELHANDLER_EXIT 0x8a0004
#define NOTESMODELHANDLER_AGENDAINTERFACE_ENTRY 0x8a0005
#define NOTESMODELHANDLER_AGENDAINTERFACE_EXIT 0x8a0006
#define NOTESMODELHANDLER_NOTESMODEL_ENTRY 0x8a0007
#define NOTESMODELHANDLER_NOTESMODEL_EXIT 0x8a0008


#endif

// End of file

