/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
* Definition of CalenEditorRepeatField class.
*
*/
// Created by TraceCompiler 2.2.4
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CALENEDITORREPEATFIELDTRACES_H__
#define __CALENEDITORREPEATFIELDTRACES_H__

#define KOstTraceComponentID 0x10207198

#define CALENEDITORREPEATFIELD_CALENEDITORREPEATFIELD_ENTRY 0x8a0132
#define CALENEDITORREPEATFIELD_CALENEDITORREPEATFIELD_EXIT 0x8a0133
#define DUP1_CALENEDITORREPEATFIELD_CALENEDITORREPEATFIELD_ENTRY 0x8a0134
#define DUP1_CALENEDITORREPEATFIELD_CALENEDITORREPEATFIELD_EXIT 0x8a0135
#define CALENEDITORREPEATFIELD_ADDITEMTOMODEL_ENTRY 0x8a0136
#define CALENEDITORREPEATFIELD_ADDITEMTOMODEL_EXIT 0x8a0137
#define CALENEDITORREPEATFIELD_REMOVEITEMFROMMODEL_ENTRY 0x8a0138
#define CALENEDITORREPEATFIELD_REMOVEITEMFROMMODEL_EXIT 0x8a0139
#define CALENEDITORREPEATFIELD_POPULATEREPEATITEM_ENTRY 0x8a013a
#define CALENEDITORREPEATFIELD_POPULATEREPEATITEM_EXIT 0x8a013b
#define CALENEDITORREPEATFIELD_HANDLEREPEATINDEXCHANGED_ENTRY 0x8a013c
#define CALENEDITORREPEATFIELD_HANDLEREPEATINDEXCHANGED_EXIT 0x8a013d
#define CALENEDITORREPEATFIELD_MODELINDEX_ENTRY 0x8a013e
#define CALENEDITORREPEATFIELD_INSERTREPEATUNTILITEM_ENTRY 0x8a013f
#define CALENEDITORREPEATFIELD_INSERTREPEATUNTILITEM_EXIT 0x8a0140
#define CALENEDITORREPEATFIELD_ISREPEATUNTILITEMADDED_ENTRY 0x8a0141
#define CALENEDITORREPEATFIELD_ISREPEATUNTILITEMADDED_EXIT 0x8a0142
#define CALENEDITORREPEATFIELD_LAUNCHREPEATUNTILDATEPICKER_ENTRY 0x8a0143
#define CALENEDITORREPEATFIELD_LAUNCHREPEATUNTILDATEPICKER_EXIT 0x8a0144
#define CALENEDITORREPEATFIELD_SETREPEATUNTILDATE_ENTRY 0x8a0145
#define CALENEDITORREPEATFIELD_SETREPEATUNTILDATE_EXIT 0x8a0146
#define CALENEDITORREPEATFIELD_REPEATUNTILDATE_ENTRY 0x8a0147
#define CALENEDITORREPEATFIELD_REPEATUNTILDATE_EXIT 0x8a0148
#define CALENEDITORREPEATFIELD_UPDATEREPEATCHOICES_ENTRY 0x8a0149
#define CALENEDITORREPEATFIELD_UPDATEREPEATCHOICES_EXIT 0x8a014a
#define DUP1_CALENEDITORREPEATFIELD_UPDATEREPEATCHOICES_EXIT 0x8a014b
#define CALENEDITORREPEATFIELD_SAVEREPEATRULE_ENTRY 0x8a014c
#define CALENEDITORREPEATFIELD_SAVEREPEATRULE_EXIT 0x8a014d
#define CALENEDITORREPEATFIELD_REMOVEREPEATUNTILITEM_ENTRY 0x8a0167
#define CALENEDITORREPEATFIELD_REMOVEREPEATUNTILITEM_EXIT 0x8a0168


#endif

// End of file

