// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __TIMEZONECLIENTTRACES_H__
#define __TIMEZONECLIENTTRACES_H__

#define KOstTraceComponentID 0x2002dd0f

#define TIMEZONECLIENT_GETINSTANCE_ENTRY 0x8a000a
#define TIMEZONECLIENT_GETINSTANCE_EXIT 0x8a000b
#define TIMEZONECLIENT_DELETEINSTANCE_ENTRY 0x8a000c
#define TIMEZONECLIENT_DELETEINSTANCE_EXIT 0x8a000d
#define TIMEZONECLIENT_ISNULL_ENTRY 0x8a000e
#define TIMEZONECLIENT_ISNULL_EXIT 0x8a000f
#define TIMEZONECLIENT_TIMEZONECLIENT_ENTRY 0x8a0010
#define TIMEZONECLIENT_TIMEZONECLIENT_EXIT 0x8a0011
#define DUP1_TIMEZONECLIENT_TIMEZONECLIENT_ENTRY 0x8a0012
#define DUP1_TIMEZONECLIENT_TIMEZONECLIENT_EXIT 0x8a0013
#define TIMEZONECLIENT_GETLOCATIONS_ENTRY 0x8a0014
#define TIMEZONECLIENT_GETLOCATIONS_EXIT 0x8a0015
#define TIMEZONECLIENT_GETUTCDSTOFFSETL_ENTRY 0x8a0016
#define TIMEZONECLIENT_GETUTCDSTOFFSETL_EXIT 0x8a0017
#define DUP1_TIMEZONECLIENT_GETUTCDSTOFFSETL_EXIT 0x8a0018
#define TIMEZONECLIENT_GETCURRENTZONEINFOL_ENTRY 0x8a0019
#define TIMEZONECLIENT_GETCURRENTZONEINFOL_EXIT 0x8a001a
#define TIMEZONECLIENT_SETASCURRENTLOCATIONL_ENTRY 0x8a001b
#define TIMEZONECLIENT_SETASCURRENTLOCATIONL_EXIT 0x8a001c
#define TIMEZONECLIENT_ISDSTONL_ENTRY 0x8a001d
#define TIMEZONECLIENT_ISDSTONL_EXIT 0x8a001e
#define TIMEZONECLIENT_GETSTANDARDOFFSET_ENTRY 0x8a001f
#define TIMEZONECLIENT_GETSTANDARDOFFSET_EXIT 0x8a0020
#define TIMEZONECLIENT_GETDSTRULESL_ENTRY 0x8a0021
#define TIMEZONECLIENT_GETDSTRULESL_EXIT 0x8a0022
#define TIMEZONECLIENT_GETSAVEDLOCATIONS_ENTRY 0x8a0023
#define TIMEZONECLIENT_GETSAVEDLOCATIONS_EXIT 0x8a0024
#define TIMEZONECLIENT_SAVELOCATIONS_ENTRY 0x8a0025
#define TIMEZONECLIENT_SAVELOCATIONS_EXIT 0x8a0026
#define DUP1_TIMEZONECLIENT_SAVELOCATIONS_EXIT 0x8a0027
#define TIMEZONECLIENT_GETCITIESFORCOUNTRY_ENTRY 0x8a0028
#define TIMEZONECLIENT_GETCITIESFORCOUNTRY_EXIT 0x8a0029
#define TIMEZONECLIENT_GETLOCATIONINFO_ENTRY 0x8a002a
#define TIMEZONECLIENT_GETLOCATIONINFO_EXIT 0x8a002b
#define _OPERATOR_ENTRY 0x8a002c
#define _OPERATOR_EXIT 0x8a002d
#define DUP1__OPERATOR_ENTRY 0x8a002e
#define DUP1__OPERATOR_EXIT 0x8a002f
#define TIMEZONECLIENT_GETDSTZONEOFFSET_ENTRY 0x8a0030
#define TIMEZONECLIENT_GETDSTZONEOFFSET_EXIT 0x8a0031
#define TIMEZONECLIENT_DSTON_ENTRY 0x8a0032
#define TIMEZONECLIENT_DSTON_EXIT 0x8a0033
#define TIMEZONECLIENT_GETCITYGROUPIDBYNAME_ENTRY 0x8a0034
#define TIMEZONECLIENT_GETCITYGROUPIDBYNAME_EXIT 0x8a0035
#define TIMEZONECLIENT_GETCITYOFFSETBYNAMEANDID_ENTRY 0x8a0036
#define TIMEZONECLIENT_GETCITYOFFSETBYNAMEANDID_EXIT 0x8a0037
#define TIMEZONECLIENT_SETDATETIME_ENTRY 0x8a0038
#define TIMEZONECLIENT_SETDATETIME_EXIT 0x8a0039
#define TIMEZONECLIENT_SETTIMEUPDATEON_ENTRY 0x8a003a
#define TIMEZONECLIENT_SETTIMEUPDATEON_EXIT 0x8a003b
#define TIMEZONECLIENT_TIMEUPDATEON_ENTRY 0x8a003c
#define TIMEZONECLIENT_TIMEUPDATEON_EXIT 0x8a003d
#define TIMEZONECLIENT_INTTOMONTH_ENTRY 0x8a003e
#define TIMEZONECLIENT_POPULATECITIES_ENTRY 0x8a003f
#define TIMEZONECLIENT_POPULATECITIES_EXIT 0x8a0040
#define TIMEZONECLIENT_CHECKFORDSTCHANGE_ENTRY 0x8a0041
#define TIMEZONECLIENT_CHECKFORDSTCHANGE_EXIT 0x8a0042
#define TIMEZONECLIENT_GETALLTIMEZONEIDS_ENTRY 0x8a0043
#define TIMEZONECLIENT_GETALLTIMEZONEIDS_EXIT 0x8a0044
#define DUP1_TIMEZONECLIENT_GETALLTIMEZONEIDS_EXIT 0x8a0045
#define TIMEZONECLIENT_GETALLTIMEZONEOFFSETS_ENTRY 0x8a0046
#define TIMEZONECLIENT_GETALLTIMEZONEOFFSETS_EXIT 0x8a0047
#define TIMEZONECLIENT_GETCOUNTRIESFORUTCOFFSET_ENTRY 0x8a0048
#define TIMEZONECLIENT_GETCOUNTRIESFORUTCOFFSET_EXIT 0x8a0049
#define TIMEZONECLIENT_ADDCITY_ENTRY 0x8a004a
#define TIMEZONECLIENT_ADDCITY_EXIT 0x8a004b
#define TIMEZONECLIENT_EVENTMONITOR_ENTRY 0x8a004c
#define TIMEZONECLIENT_EVENTMONITOR_EXIT 0x8a004d
#define TIMEZONECLIENT_NOTIFYTIMECHANGE_ENTRY 0x8a004e
#define TIMEZONECLIENT_NOTIFYTIMECHANGE_EXIT 0x8a004f


#ifndef __OSTTRACEGEN2_TUINT32_TUINT_TUINT__
#define __OSTTRACEGEN2_TUINT32_TUINT_TUINT__

inline TBool OstTraceGen2( TUint32 aTraceID, TUint aParam1, TUint aParam2 )
    {
    TBool retval = BTraceFiltered8( EXTRACT_GROUP_ID(aTraceID), EOstTraceActivationQuery, KOstTraceComponentID, aTraceID );
    if ( retval )
        {
        TUint8 data[ 8 ];
        TUint8* ptr = data;
        *( ( TUint* )ptr ) = aParam1;
        ptr += sizeof ( TUint );
        *( ( TUint* )ptr ) = aParam2;
        ptr += sizeof ( TUint );
        ptr -= 8;
        retval = OstSendNBytes( EXTRACT_GROUP_ID(aTraceID), EOstTrace, KOstTraceComponentID, aTraceID, ptr, 8 );
        }
    return retval;
    }

#endif // __OSTTRACEGEN2_TUINT32_TUINT_TUINT__


#ifndef __OSTTRACEGEN2_TUINT32_TUINT32_TUINT32__
#define __OSTTRACEGEN2_TUINT32_TUINT32_TUINT32__

inline TBool OstTraceGen2( TUint32 aTraceID, TUint32 aParam1, TUint32 aParam2 )
    {
    TBool retval = BTraceFiltered8( EXTRACT_GROUP_ID(aTraceID), EOstTraceActivationQuery, KOstTraceComponentID, aTraceID );
    if ( retval )
        {
        TUint8 data[ 8 ];
        TUint8* ptr = data;
        *( ( TUint* )ptr ) = aParam1;
        ptr += sizeof ( TUint );
        *( ( TUint* )ptr ) = aParam2;
        ptr += sizeof ( TUint );
        ptr -= 8;
        retval = OstSendNBytes( EXTRACT_GROUP_ID(aTraceID), EOstTrace, KOstTraceComponentID, aTraceID, ptr, 8 );
        }
    return retval;
    }

#endif // __OSTTRACEGEN2_TUINT32_TUINT32_TUINT32__



#ifndef __OSTTRACEGEN2_TUINT32_TUINT_TINT__
#define __OSTTRACEGEN2_TUINT32_TUINT_TINT__

inline TBool OstTraceGen2( TUint32 aTraceID, TUint aParam1, TInt aParam2 )
    {
    TBool retval = BTraceFiltered8( EXTRACT_GROUP_ID(aTraceID), EOstTraceActivationQuery, KOstTraceComponentID, aTraceID );
    if ( retval )
        {
        TUint8 data[ 8 ];
        TUint8* ptr = data;
        *( ( TUint* )ptr ) = aParam1;
        ptr += sizeof ( TUint );
        *( ( TInt* )ptr ) = aParam2;
        ptr += sizeof ( TInt );
        ptr -= 8;
        retval = OstSendNBytes( EXTRACT_GROUP_ID(aTraceID), EOstTrace, KOstTraceComponentID, aTraceID, ptr, 8 );
        }
    return retval;
    }

#endif // __OSTTRACEGEN2_TUINT32_TUINT_TINT__


#ifndef __OSTTRACEGEN2_TUINT32_TUINT32_TINT32__
#define __OSTTRACEGEN2_TUINT32_TUINT32_TINT32__

inline TBool OstTraceGen2( TUint32 aTraceID, TUint32 aParam1, TInt32 aParam2 )
    {
    TBool retval = BTraceFiltered8( EXTRACT_GROUP_ID(aTraceID), EOstTraceActivationQuery, KOstTraceComponentID, aTraceID );
    if ( retval )
        {
        TUint8 data[ 8 ];
        TUint8* ptr = data;
        *( ( TUint* )ptr ) = aParam1;
        ptr += sizeof ( TUint );
        *( ( TInt* )ptr ) = aParam2;
        ptr += sizeof ( TInt );
        ptr -= 8;
        retval = OstSendNBytes( EXTRACT_GROUP_ID(aTraceID), EOstTrace, KOstTraceComponentID, aTraceID, ptr, 8 );
        }
    return retval;
    }

#endif // __OSTTRACEGEN2_TUINT32_TUINT32_TINT32__



#endif

// End of file

