///*
//* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
//* All rights reserved.
//* This component and the accompanying materials are made available
//* under the terms of the License "Eclipse Public License v1.0"
//* which accompanies this distribution, and is available
//* at the URL "http://www.eclipse.org/legal/epl-v10.html".
//*
//* Initial Contributors:
//* Nokia Corporation - initial contribution.
//*
//* Contributors:
//*
//* Description: 
//*
//*/

ANY_DRIVE "anydrive"

// emulator use 1: x, 2: t or some other drives that do work.

DRIVE_1  f
DRIVE_2  e
DRIVE_3  c

C_DRIVE c
E_DRIVE e
F_DRIVE f
