///*
//* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
//* All rights reserved.
//* This component and the accompanying materials are made available
//* under the terms of the License "Eclipse Public License v1.0"
//* which accompanies this distribution, and is available
//* at the URL "http://www.eclipse.org/legal/epl-v10.html".
//*
//* Initial Contributors:
//* Nokia Corporation - initial contribution.
//*
//* Contributors:
//*
//* Description: 
//*
//*/

KVcxTestErrNotFound                -1111
KVcxTestErrVerifyFailed            -1112

KERRNONE                                        0         
KERRNOTFOUND                                    -1        
KERRGENERAL                                     -2        
KERRCANCEL                                      -3
KERRNOMEMORY                                    -4        
KERRNOTSUPPORTED                                -5        
KERRARGUMENT                                    -6        
KERRBADHANDLE                                   -8
KERROVERFLOW                                    -9        
KERRUNDERFLOW                                   -10        
KERRALREADYEXISTS                               -11
KERRINUSE                                       -14
KERRSERVERBUSY                                  -16
KERRNOTREADY                                    -18
KERRUNKNOWN                                     -19
KERRCORRUPT                                     -20
KERRLOCKED                                      -22
KERRDISKFULL                                    -26
KERRBADNAME                                     -28
KERRTIMEDOUT                                    -33
KERRABORT                                       -39
KERRTOOBIG                                      -40
KErrCouldNotConnect                             -34
