######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 3 15:16:30 2009
######################################################################

TEMPLATE = subdirs
SUBDIRS += alarmalertwidget
CONFIG += ordered

BLD_INF_RULES.prj_mmpfiles += "./group/AlmAlert.mmp" \
							  "./group/AknAlarmService.mmp"
							  
BLD_INF_RULES.prj_exports += "$${LITERAL_HASH}include <platform_paths.hrh>" \
							 "./rom/AlmAlert.iby			CORE_APP_LAYER_IBY_EXPORT_PATH(AlmAlert.iby)" \
							 "./rom/AlmAlertResources.iby	LANGUAGE_APP_LAYER_IBY_EXPORT_PATH(AlmAlertResources.iby)" \
							 "./loc/AlmAlert.loc			APP_LAYER_LOC_EXPORT_PATH(AlmAlert.loc)" \
							 "./group/alarmuisnooze.rul		/epoc32/release/winscw/udeb/z/private/10282bc4/rules/alarmuisnooze.rul" \
							 "./group/alarmuisnooze.rul		/epoc32/release/winscw/urel/z/private/10282bc4/rules/alarmuisnooze.rul" \
							 "./group/alarmuisnooze.rul		/epoc32/data/z/private/10282bc4/rules/alarmuisnooze.rul" \
							 "./DataSrc/alarm.aac			/epoc32/release/winscw/udeb/z/data/sounds/digital/alarm.aac" \
							 "./DataSrc/clock.aac			/epoc32/release/winscw/udeb/z/data/sounds/digital/clock.aac" \
							 "./DataSrc/alarm.aac			/epoc32/release/winscw/urel/z/data/sounds/digital/alarm.aac" \
							 "./DataSrc/clock.aac			/epoc32/release/winscw/urel/z/data/sounds/digital/clock.aac" \
							 "./DataSrc/alarm.aac			/epoc32/data/z/data/sounds/digital/alarm.aac" \
							 "./DataSrc/clock.aac			/epoc32/data/z/data/sounds/digital/clock.aac" \
							 "./stubsis/alarmui_stub.sis	/epoc32/data/z/system/install/alarmui_stub.sis"
