// Copyright (c) 2000-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// Generated by CalconTable.exe
//

const TInt KFirstCycle=77;//1..n
const TInt KFirstJulianDate=2444240;
const TInt KLastJulianDate=2488434;
const TInt KFirstYear=56; //1..60
const TInt KLastCycle=79;//1..n
const TInt KLastYear=57;//1..60
const TInt KNumberOfYears=122;
