// Created by TraceCompiler 2.2.3
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __CLOCKSETTINGSVIEWPLUGINTRACES_H__
#define __CLOCKSETTINGSVIEWPLUGINTRACES_H__

#define KOstTraceComponentID 0x2003157c

#define CLOCKSETTINGSVIEWPLUGIN_CLOCKSETTINGSVIEWPLUGIN_ENTRY 0x8a0001
#define CLOCKSETTINGSVIEWPLUGIN_CLOCKSETTINGSVIEWPLUGIN_EXIT 0x8a0002
#define DUP1_CLOCKSETTINGSVIEWPLUGIN_CLOCKSETTINGSVIEWPLUGIN_ENTRY 0x8a0003
#define DUP1_CLOCKSETTINGSVIEWPLUGIN_CLOCKSETTINGSVIEWPLUGIN_EXIT 0x8a0004
#define CLOCKSETTINGSVIEWPLUGIN_LAUNCHREGIONALSETTINGSVIEW_ENTRY 0x8a0005
#define CLOCKSETTINGSVIEWPLUGIN_LAUNCHREGIONALSETTINGSVIEW_EXIT 0x8a0006


#endif

// End of file

