// Copyright (c) 2006-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// popservermtm module header
// 
//

/**
 @file
 @internalComponent
 @released
*/


#ifndef __POPSMBX_H__
#define __POPSMBX_H__
// Leave these constants in this file to keep BC, as file is exported
const TInt KMsgPop3RefreshMailboxPriority = 1;
const TUid KMsgFileRemoteIdIndex ={0x100002F9};

const TInt KImMailMaxIdLength = 200;
const TInt KPop3RefreshUidlEquate=1;

#endif
